Supported PSR-7 in File\Count validator
laminas/laminas-validator pull request #109
Opened 2021-09-09 13:34 UTC by icetee

|    Q          |   A
|-------------- | ------
| Documentation | no
| Bugfix        | yes
| BC Break      | no
| New Feature   | no
| RFC           | no
| QA            | no

### Description
This PR complements previous PR https://github.com/zendframework/zend-validator/pull/251. Recommendation PSR-7 UploadedFileInterface has not been implemented in File / Count validation. At the same time, it improves the https://github.com/laminas/laminas-validator/issues/24 issue.

2022-10-11 13:00 UTC, Ocramius requested changes
I like this: good improvement.

Missing an unhappy path with an `UploadedFileInterface` though :thinking:

2022-10-11 13:00 UTC, Ocramius commented
Also: sorry for not noticing the patch before :\

2022-10-11 14:03 UTC, icetee commented
I need to change something? @Ocramius

2022-10-11 14:06 UTC, Ocramius commented
I think a `false` scenario in the validator test would be good here

2022-10-16 22:57 UTC, icetee commented
I updated the base version (2.27.x), let's continue here #158

2022-10-16 22:57 UTC, closed without merging