QA: Bumps Dependencies and Improves Static Analysis
laminas/laminas-validator pull request #129
Opened 2022-06-13 20:54 UTC by gsteel

|    Q          |   A
|-------------- | ------
| QA            | yes

### Description

- Drops PHP 7.3
- Drops Service Manager v2
- Updates latest dev dependencies
- Adds template types for plugin manager
- Fixes newly surfaced type errors

2022-06-13 22:27 UTC, Ocramius requested changes

2022-06-13 22:27 UTC, Ocramius commented on src/ValidatorPluginManager.php
> +        \zend\validator\csrf::class         => Csrf::class,
To be reverted

2022-06-14 00:04 UTC, gsteel commented on src/ValidatorPluginManager.php
> +        \zend\validator\csrf::class         => Csrf::class,
Eagle eyes! I'm blaming `phpcbf` for that!

2022-06-14 06:07 UTC, boesing requested changes
Can you also replace the interop containers with PSR? that would be decent.

If this component does require interop as a composer dependency, this can be dropped as well 👌🏻

2 birds with one stone ❤️

2022-06-14 06:07 UTC, boesing commented on src/ValidatorPluginManager.php
> +use Interop\Container\ContainerInterface; // phpcs:ignore
Should become PSR since we dropped interop with one of the servicemanager versions.

2022-06-14 07:17 UTC, gsteel commented
Is something wrong with the [laminas-ci action](https://github.com/laminas/laminas-continuous-integration-action/releases) 1.20 release? - Everything is passing locally

2022-06-14 07:18 UTC, Ocramius commented
Yup: new got version broke everything 😩

We need to patch it to add https://stackoverflow.com/questions/71849415/i-cannot-add-the-parent-directory-to-safe-directory-in-git/71904131#71904131 to it.

2022-06-14 07:59 UTC, Ocramius commented
FWIW, raised https://github.com/laminas/laminas-continuous-integration-action/pull/95, need a review :)

2022-06-14 08:22 UTC, Ocramius approved these changes

2022-06-14 12:30 UTC, Ocramius approved these changes
:ship: thanks @gsteel!

2022-06-14 12:30 UTC, merged