8.2 fwd compat
laminas/laminas-validator pull request #149
Opened 2022-09-12 10:55 UTC by gsteel

|    Q          |   A
|-------------- | ------
| Bugfix        | yes
| QA            | yes

### Description

Testing a local project under 8.2-RC reveals a problem specific to the Date validator, where `DateTime::getLastErrors()` is potentially false. Even given https://3v4l.org/HBq0q - I still can't seem to get a test to actually return false from this method, so verifying the fix is a tough one. Any ideas?

A couple of other tests had complaints about dynamic properties and I've silenced a number of tests that don't perform any assertions depending on the data providers.

2022-09-12 13:57 UTC, boesing requested changes
Does psalm already support that `false` return value of `DateTime#getLastErrors`? 

If so, its absolutely okay to early return without actually having a test which verifies if the methods return value is `false` is due to the fact that `DateTime::getLastErrors` returns an array with `warning_count`/`error_count` being positive-int  or due to the return value `false`.

Overall, LGTM.

2022-09-12 13:57 UTC, boesing commented on psalm-baseline.xml
> +<files psalm-version="4.26.0@6998fabb2bf528b65777bf9941920888d23c03ac">
cant we already bump to v4.27?

2022-09-12 13:57 UTC, boesing commented on test/File/ExcludeExtensionTest.php
> +            $this->expectNotToPerformAssertions();
Can we probably change the check above to ensure test is only executed incase of an array and if its not an error, mark it as skipped? 

Feels weird if we assert there are no assertions if there is actually nothing tested.

Skipped message could be something like `only array foo is being tested for legacy whatever`.

2022-09-12 13:57 UTC, boesing commented on test/File/ExistsTest.php
> +            $this->expectNotToPerformAssertions();
Can we probably change the check above to ensure test is only executed incase of an array and if its not an error, mark it as skipped? 

Feels weird if we assert there are no assertions if there is actually nothing tested.

Skipped message could be something like `only array foo is being tested for legacy whatever`.

2022-09-12 13:57 UTC, boesing commented on test/File/ExtensionTest.php
> +            $this->expectNotToPerformAssertions();
Can we probably change the check above to ensure test is only executed incase of an array and if its not an error, mark it as skipped? 

Feels weird if we assert there are no assertions if there is actually nothing tested.

Skipped message could be something like `only array foo is being tested for legacy whatever`.

2022-09-12 13:57 UTC, boesing commented on test/File/HashTest.php
> +            $this->expectNotToPerformAssertions();
Can we probably change the check above to ensure test is only executed incase of an array and if its not an error, mark it as skipped? 

Feels weird if we assert there are no assertions if there is actually nothing tested.

Skipped message could be something like `only array foo is being tested for legacy whatever`.

2022-09-12 13:57 UTC, boesing commented on test/File/ImageSizeTest.php
> +            $this->expectNotToPerformAssertions();
Can we probably change the check above to ensure test is only executed incase of an array and if its not an error, mark it as skipped? 

Feels weird if we assert there are no assertions if there is actually nothing tested.

Skipped message could be something like `only array foo is being tested for legacy whatever`.

2022-09-12 13:57 UTC, boesing commented on test/File/Md5Test.php
> +            $this->expectNotToPerformAssertions();
Can we probably change the check above to ensure test is only executed incase of an array and if its not an error, mark it as skipped? 

Feels weird if we assert there are no assertions if there is actually nothing tested.

Skipped message could be something like `only array foo is being tested for legacy whatever`.

2022-09-12 13:57 UTC, boesing commented on test/File/NotExistsTest.php
> +            $this->expectNotToPerformAssertions();
Can we probably change the check above to ensure test is only executed incase of an array and if its not an error, mark it as skipped? 

Feels weird if we assert there are no assertions if there is actually nothing tested.

Skipped message could be something like `only array foo is being tested for legacy whatever`.

2022-09-12 13:57 UTC, boesing commented on test/File/Sha1Test.php
> +            $this->expectNotToPerformAssertions();
Can we probably change the check above to ensure test is only executed incase of an array and if its not an error, mark it as skipped? 

Feels weird if we assert there are no assertions if there is actually nothing tested.

Skipped message could be something like `only array foo is being tested for legacy whatever`.

2022-09-12 13:57 UTC, boesing commented on test/File/SizeTest.php
> +            $this->expectNotToPerformAssertions();
Can we probably change the check above to ensure test is only executed incase of an array and if its not an error, mark it as skipped? 

Feels weird if we assert there are no assertions if there is actually nothing tested.

Skipped message could be something like `only array foo is being tested for legacy whatever`.

2022-09-12 13:57 UTC, boesing commented on test/File/WordCountTest.php
> +            $this->expectNotToPerformAssertions();
Can we probably change the check above to ensure test is only executed incase of an array and if its not an error, mark it as skipped? 

Feels weird if we assert there are no assertions if there is actually nothing tested.

Skipped message could be something like `only array foo is being tested for legacy whatever`.

2022-09-12 13:57 UTC, boesing commented on test/File/Crc32Test.php
> +            $this->expectNotToPerformAssertions();
Can we probably change the check above to ensure test is only executed incase of an array and if its not an error, mark it as skipped? 

Feels weird if we assert there are no assertions if there is actually nothing tested.

Skipped message could be something like `only array foo is being tested for legacy whatever`.

2022-09-12 14:21 UTC, gsteel commented
Related: https://github.com/vimeo/psalm/pull/8478

2022-09-12 14:31 UTC, gsteel commented on psalm-baseline.xml
> +<files psalm-version="4.26.0@6998fabb2bf528b65777bf9941920888d23c03ac">
I can do that separately - I didn't want the noise in this pull

2022-09-12 14:33 UTC, gsteel commented on test/File/ExcludeExtensionTest.php
> +            $this->expectNotToPerformAssertions();
Yep - that was laziness on my part. All relevant tests adjusted to skip non-array args.

2022-09-12 17:43 UTC, boesing commented
@gsteel you actually have to enable `ignoreInternalFunctionFalseReturn` in psalm config.

Sadly, thats not enabled by default.

Ref: https://github.com/vimeo/psalm/pull/7758#issuecomment-1228577723

2022-09-12 18:31 UTC, gsteel commented
@boesing - this should be good to go. The conditional in `Date` validator is required for PHP 8.2 though due to real errors such as `array offset on bool`… so I guess we'll just leave it in the baseline.

I did take a quick look at disabling `ignoreInternalFunctionFalseReturn` in `psalm.xml` but that yielded another 200 errors. Happy to disable it and expand the baseline if you'd like to see that here?

Is it worth trawling through the options and coming up with a standard config for all of the components do you think?

2022-09-13 07:26 UTC, Ocramius commented
> Is it worth trawling through the options and coming up with a standard config for all of the components do you think?

Yes, but not here :D

2022-09-13 07:26 UTC, Ocramius approved these changes
LGTM, thanks @gsteel!

2022-09-13 07:27 UTC, merged