add handling for enum as haystack
laminas/laminas-validator pull request #168
Opened 2022-12-29 22:06 UTC by reinfi

Signed-off-by: Reinfi <reinfandt@z-em.de>

|    Q          |   A
|-------------- | ------
| Documentation | no
| Bugfix        | no
| BC Break      | no
| New Feature   | yes
| RFC           | no
| QA            | no

### Description

See issue #167.

Suggestion was to allow the haystack to be an enum. Otherwise a new validator for just the case of enums would be suitable.

I am a bit unsure about the testcase and I hope it would work with the build pipeline, but I will see it afterwards. 

Happy to hear your feedback.

2022-12-30 03:02 UTC, Ocramius commented on src/InArray.php
> +     * @var array|class-string<UnitEnum>
Ok, from a preliminary observation, I think we should leave the haystack alone, and just populate it from a new option containing the enum.

Changing the haystack itself is probably more trouble, especially for BC.

This also means having a new private `setEnum()` or such 🤔

2022-12-30 03:02 UTC, Ocramius requested changes
Ok, from a preliminary observation, I think we should leave the haystack alone, and just populate it from a new option containing the enum.

Changing the haystack itself is probably more trouble, especially for BC.

This also means having a new private `setEnum()` or such 🤔

2022-12-30 18:51 UTC, reinfi commented
Still Psalm will fail, but I have not really an idea how to handle that because I had nothing todo with psalm so far 🙈

2023-01-02 01:06 UTC, Ocramius reviewed
Overall, approach seems OK 👍 

What I'm thinking about is how to get static analysis "happy" with this :D 

 > Still Psalm will fail, but I have not really an idea how to handle that because I had nothing todo with psalm so far 🙈

We could use a `.stub` file with Psalm, for now, perhaps: we'd declare `BackedEnum` there, then drop the stub once we drop PHP 8.0 support 🤔 

/cc @gsteel do you have any ideas?

2023-01-02 01:06 UTC, Ocramius commented on src/InArray.php
> +        if (! is_subclass_of($enum, UnitEnum::class)) {
I think we can skip this particular check: `class-string<UnitEnum>` already verifies this, and code written in newer codebases generally respects types in a much cleaner way

2023-01-02 01:06 UTC, Ocramius commented on src/InArray.php
> +    protected $enum;
Let's make this `private` before it spreads :D

2023-01-02 01:06 UTC, Ocramius commented on src/InArray.php
> +        $enum = $this->getEnum();
Since we make `$this->enum` `private`, we can directly access it here: no need for a method call

2023-01-02 01:06 UTC, Ocramius commented on src/InArray.php
> +        if (is_string($enum)) {
We should just check for  `!== null`

2023-01-02 01:06 UTC, Ocramius commented on src/InArray.php
> +    }
I wonder if this method should call `setHaystack()`: that would remove the need for touching the `isValid()` implementation

2023-01-03 07:53 UTC, boesing commented
@Ocramius one things we need to keep in mind is that filters and stuff are usually passed as attributes and/or annotations. I am working with these Interfaces for years now and I have never called setters directly. They are always called from provided factories from within this component and thus I only have to use the attributes/annotations which allow devs to declare a spec which then is processed. Thats why the abstract filter is used because options are being passed as array so that they can be passed to the plugin manager. thats why the "build" method has that optional options array.

2024-07-29 21:20 UTC, closed without merging