Fix #135: better GPS point validator detection of invalid coordinate numeric conversions
laminas/laminas-validator pull request #169
Opened 2023-01-12 09:37 UTC by codisart

|    Q          |   A
|-------------- | ------
| Bugfix        | yes
| BC Break      | yes

### Description

This PR is trying to fix the issue #135. 
The fix is to have the string "foo" not converted to 0.0 and validated as a correct coordinate.

2023-01-12 15:17 UTC, Ocramius requested changes
Please check CI failures too

2023-01-12 15:17 UTC, Ocramius commented on src/GpsPoint.php
> +        if ($value === false || $value === null || !is_numeric($value)) {
This ternary can be simplified to just the `is_numeric()` check

2023-01-12 15:17 UTC, Ocramius commented on test/GPSPointTest.php
> +     * @psalm-return array<array-key, arrayG{0: string}>
A `G` slipped in

2023-01-12 15:18 UTC, Ocramius commented
As this is a bugfix, it should target `2.29.x`

2023-01-12 15:22 UTC, froschdesign commented on test/GPSPointTest.php
> +            ['65° 4\' N,-22.728867530822754', GpsPoint::CONVERT_ERROR, '65° 4\' N'],
The previous test was fine, so out of bounds cannot be a conversion error now!

2023-01-12 15:23 UTC, froschdesign commented on test/GPSPointTest.php
> +            ['65° 4\' N,-22.728867530822754', GpsPoint::CONVERT_ERROR, '65° 4\' N'],
See my comment on the related issue report: https://github.com/laminas/laminas-validator/issues/135#issuecomment-1165290208

2023-01-12 15:35 UTC, codisart commented on test/GPSPointTest.php
> +     * @psalm-return array<array-key, arrayG{0: string}>
Thank you, I removed it

2023-01-12 16:01 UTC, codisart commented on test/GPSPointTest.php
> +            ['65° 4\' N,-22.728867530822754', GpsPoint::CONVERT_ERROR, '65° 4\' N'],
Hello @froschdesign, this change in the provider is a mistake for this PR.
I have a new fix where I use the casting to float to determine is the previous string was a partial number.

2023-01-12 16:30 UTC, codisart commented on test/GPSPointTest.php
> +            ['65° 4\' N,-22.728867530822754', GpsPoint::CONVERT_ERROR, '65° 4\' N'],
Hello @froschdesign, this change in the provider is a mistake for this PR.
I have a new fix where I use the casting to float to determine is the previous string was a partial number before the casting.

2023-01-12 16:30 UTC, codisart commented on src/GpsPoint.php
> +        if ($value === false || $value === null || !is_numeric($value)) {
After the comment of froschdesign, this check has became obsolete.

2024-02-22 10:25 UTC, Ocramius approved these changes
Thanks @codisart!

2024-02-22 10:26 UTC, merged