Introduce `IsJsonString` validator
laminas/laminas-validator pull request #172
Opened 2023-01-26 15:52 UTC by gsteel

|    Q          |   A
|-------------- | ------
| New Feature   | yes

### Description

Adds a straight-forward validator to help determine if a string would successfully decode to JSON.

Provides options for limiting acceptable input, or rather the acceptable types the json would decode to and an option for max depth.

I was surprised to not find something like this already here!

2023-01-26 17:46 UTC, boesing commented
Can we probably keep maintenance in dedicated tickets rather than adding them to a feature?
Since we do not put effort into changelogs and thus these usually contain the PR title, as a user, I'd not expect anything else to change but having a new validator available.

This PR does plenty of other stuff (such as refining types, etc.) and thus I'd really encourage you to put that QA stuff into a dedicated PR.

2023-01-26 18:30 UTC, gsteel commented
Acknowledged @boesing - I was just trying to get CI green here on unrelated issues. I'll revert to the bare minimum to get a thumbs up from psalm on locked deps tomorrow.

2023-01-26 18:51 UTC, froschdesign commented
> Since we do not put effort into changelogs and thus these usually contain the PR title…

**This is absolutely correct!** 

If we look at [the latest release notes of laminas-view](https://github.com/laminas/laminas-view/releases/tag/2.26.0), the information they contain is poor and useless for a user:

> ### Enhancement
> Remove laminas/console dev dependency and stop ignoring platform requirements

Does this mean that something no longer works and why was this removed in a minor version?

> ### Documentation,Enhancement
> Merge release 2.25.1 into 2.26.x
> ### Bug,Documentation
> Merge release 2.25.2 into 2.26.x

What does that mean? Does this bring me anything as a user or why is this information included in a release note?

2023-01-26 18:54 UTC, froschdesign commented
@gsteel 
I like it a lot and also that different types can be allowed! 👍🏻

2023-01-26 22:34 UTC, froschdesign requested changes

2023-01-26 22:34 UTC, froschdesign commented on docs/book/validators/is-json-string.md
> +# IsJsonString Validator
The first headline must be synchronised with the navigation entry.

```suggestion
# IsJsonString
```

_(Right, that's not true for most of the other pages.)_

2023-01-26 22:34 UTC, froschdesign commented on docs/book/validators/is-json-string.md
> +## Restricting Acceptable JSON types
```suggestion
## Restricting Acceptable JSON Types
```

2023-01-26 22:34 UTC, froschdesign commented on docs/book/validators/is-json-string.md
> +- `IsJsonString::ALLOW_BOOL` - Accept "true" and "false"
```suggestion
- `IsJsonString::ALLOW_INT` - Accept integer such as `1`
- `IsJsonString::ALLOW_FLOAT` - Accept floating-point value such as `1.234`
- `IsJsonString::ALLOW_BOOL` - Accept `true` and `false`
```

2023-01-26 22:34 UTC, froschdesign commented on docs/book/validators/is-json-string.md
> +$validator->isValid("1.234"); // false
```suggestion
$validator->isValid('1.234'); // false
```

2023-01-27 12:53 UTC, froschdesign approved these changes
Looks good to me! 👍🏻 

(I have already updated the milestone description).

2023-01-27 14:21 UTC, Ocramius requested changes

2023-01-27 14:21 UTC, Ocramius commented on src/IsJsonString.php
> +    public const ALLOW_INT    = 0b0000001;
IMO the validator is called "IsJsonString", so if non-string input is given, it should just fail, no other complexity needed (ambiguous otherwise)

2023-01-27 14:23 UTC, gsteel commented on src/IsJsonString.php
> +    public const ALLOW_INT    = 0b0000001;
It does fail when given a non string - the 'allow' represents JSON strings in the form "1.2", "1", "true", "false", "[]", and "{}"

2023-01-27 14:27 UTC, Ocramius commented on src/IsJsonString.php
> +    public const ALLOW_INT    = 0b0000001;
Hmm, I'm not convinced we should do this sort of validation in here 🤔

Anyway, if "allow all" is the default, I'm OK with this patch (sorry, only doing reviews from my phone, while on the run 😬)

2023-01-27 14:31 UTC, gsteel commented on src/IsJsonString.php
> +    public const ALLOW_INT    = 0b0000001;
Allow all is the default. The general idea here is "Will it decode or not?" - The ALLOW_* constants allow you fine tune the guard so that you can say, "I only want JSON objects to pass validation" fe.

2023-01-30 21:33 UTC, Ocramius approved these changes
@gsteel if you were waiting for me to merge, sorry, here's my approval meanwhile :D

2023-01-30 22:18 UTC, merged