Fix value annotation in isValid method for Regex validator.
laminas/laminas-validator pull request #179
Opened 2023-02-23 13:11 UTC by h3nnry

Changed annotation for parameter value in isValid method for Regex validator, from string to string|numerical as long as this method accepts also integer and float parameters.

2023-02-23 14:46 UTC, Ocramius requested changes

2023-02-23 14:46 UTC, Ocramius commented on src/Regex.php
> +        /** @psalm-suppress PossiblyInvalidArgument */
Not acceptable here

2023-02-23 14:46 UTC, Ocramius commented on src/Regex.php
> +     * @param  string|numeric $value
If we accept non-string values, a string cast is probably needed for acceptable conversions

2023-02-23 19:09 UTC, h3nnry commented on src/Regex.php
> +        /** @psalm-suppress PossiblyInvalidArgument */
removed.

2023-02-23 19:09 UTC, h3nnry commented on src/Regex.php
> +     * @param  string|numeric $value
added.

2023-02-24 16:51 UTC, Ocramius requested changes

2023-02-24 16:51 UTC, Ocramius commented on src/Regex.php
> +        }
Since new logic was added, we should have a test covering this scenario?

2023-03-02 16:59 UTC, h3nnry commented on src/Regex.php
> +        }
added

2023-03-02 19:26 UTC, Ocramius approved these changes
LGTM, although asking for another review by others.

2023-03-02 20:41 UTC, internalsystemerror commented on src/Regex.php
> +        }
I have reservations against allowing floats for the same reasons it was removed from moneyphp (I believe by @Ocramius), and as was discussed here: https://github.com/moneyphp/money/issues/650.

This would then be cast as a responsibility of the user to handle that.
```php
$regExValidator->isValid((string)$value);
```

Maybe there needs to be a `ToString` filter for use with [`laminas/laminas-input-filter`](https://github.com/laminas/laminas-inputfilter)?

Although not as immediately important as with a package named `money`, since this is for validation I could see some users unknowingly making a mistake. Thoughts? Is this an overreaction?

2023-03-02 20:44 UTC, internalsystemerror reviewed
https://github.com/laminas/laminas-validator/pull/179#discussion_r1123668853 is my only reservation. But if people that's overcautious then I'm happy to approve.

2023-03-02 21:13 UTC, Ocramius commented on src/Regex.php
> +        }
Ooooh, that is a good point! A floating point number may indeed cast to something unexpected 🤔

2023-03-02 21:28 UTC, froschdesign commented on src/Regex.php
> +        }
@internalsystemerror 
> Maybe there needs to be a ToString filter…

See: https://github.com/laminas/laminas-filter/issues/98

2023-03-02 21:51 UTC, gsteel requested changes

2023-03-02 21:51 UTC, gsteel commented on src/Regex.php
> +     * @param  string|numeric $value
IMO, `isValid()` should always accept `mixed` as per [the interface](https://github.com/laminas/laminas-validator/blob/2.31.x/src/ValidatorInterface.php).

2023-03-02 21:51 UTC, gsteel commented on src/Regex.php
> +        }
I don't think we can restrict the input type of the validator beyond `mixed` to begin with, so I think that the string cast is necessary to preserve existing behaviour. In hind-sight, the first conditional should have failed on any non-string value, but as it doesn't, at least the cast prevents `int|float` reaching `preg_match`

2023-03-02 21:51 UTC, gsteel commented on test/RegexTest.php
> +    }
Can we also add some failures here too by adding the pattern to the data provider such as `[123.45, '/^\d+$/', false]`? _(also make it static for PHPUnit 10)_

2023-03-03 09:41 UTC, h3nnry commented on test/RegexTest.php
> +    }
added.

2023-03-03 10:02 UTC, gsteel commented on test/RegexTest.php
> +    }
Thanks @h3nnry

2023-03-03 11:17 UTC, Ocramius commented on src/Regex.php
> +        }
The only scenario I'm worried about here is a string cast for stuff that ends up being `1.07E-5` or such :thinking:

2023-03-03 11:20 UTC, h3nnry commented on src/Regex.php
> +     * @param  string|numeric $value
In my opinion bette to avoid mixed type.

2023-03-03 11:30 UTC, h3nnry commented on src/Regex.php
> +        }
In my opinion it's user who need to avoid scientific notation, and if he's ok with it it need to created the correct pattern.

2023-03-03 11:32 UTC, Ocramius commented on src/Regex.php
> +        }
A `(string)` cast of a `float` value may lead to the scientific notation regardless.

2023-03-03 11:40 UTC, gsteel commented on src/Regex.php
> +        }
Yeah - I get that concern, but there's already an implicit cast to string during `preg_match` anyhow. I think the only way to "fix" this is to reject int|float up-front and I don't think we can get away with that due to existing behaviour.

Perhaps a note should be added to remove the int|float checks for the next major and fail non-string input, making it the callers responsibility to cast if necessary, leaving the current implementation broken in the same predictable way.

My understanding is that this patch does nothing to change the existing behaviour, i.e:

```php
preg_match('/^\d{1}\.\d{2}$/', 0.01); // 1
preg_match('/^\d{1}\.\d{2}$/', '0.01'); // 1
preg_match('/^\d{1}\.\d{2}$/', 35 + -34.99); // 0
preg_match('/^\d{1}\.\d{2}$/', '35' + '-34.99'); // 0
```

2023-03-03 14:08 UTC, internalsystemerror commented on src/Regex.php
> +        }
If it's currently broken because there is no parameter type hint then I don't think we can "fix" it. But we CAN prevent people from making the mistake if they're intending to use static analysis.

I was thinking we use `@param string|int` instead of `@param string|int|float` more than any specific handling using `is_float`. Though now that consider @gsteel's position, I guess validators will always be required to accept a value of mixed type, so should it be throwing an error (by setting a parameter type hint in a future major), or should it just be returning false?

If the latter then it should stay as mixed and then `if(!is_string($value) && !is_int($value)) { return false; }`?

2023-03-03 16:03 UTC, Ocramius commented on src/Regex.php
> +        }
Beware that the interface does indeed say `mixed`:

https://github.com/laminas/laminas-validator/blob/b904e5d197633e0eeb4c0162d8e7604e8829d10a/src/ValidatorInterface.php#L22-L26

2024-06-25 21:53 UTC, gsteel commented
Thanks for your work here @h3nnry - #280 has been merged into 3.0.x, so I think this PR is no longer relevant.

2024-06-25 21:53 UTC, closed without merging