allow use of TranslatorInterface as Translator
laminas/laminas-validator pull request #224
Opened 2024-01-13 11:52 UTC by mimmi20

|    Q          |   A
|-------------- | ------
| Documentation | no
| Bugfix        | yes
| BC Break      | no
| New Feature   | no
| RFC           | no
| QA            | no

### Description

This PR wants to allow the use of `Laminas\I18n\Translator\TranslatorInterface` if 'MvcTranslator' is not available.
This is related to #194.

2024-01-13 11:59 UTC, froschdesign commented
@mimmi20 
Please note: `Laminas\Validator\Translator\TranslatorInterface` !== `Laminas\I18n\Translator\TranslatorInterface`

https://github.com/laminas/laminas-validator/blob/bbb318490d186821e9488dcbc24455e1578717bb/src/Translator/TranslatorInterface.php#L3-L14

vs.

https://github.com/laminas/laminas-i18n/blob/99c7f8a2e1b286db71bee80f39f78b7d3c53d5d1/src/Translator/TranslatorInterface.php#L3-L18

2024-01-13 12:18 UTC, mimmi20 commented
> @mimmi20 Please note: `Laminas\Validator\Translator\TranslatorInterface` !== `Laminas\I18n\Translator\TranslatorInterface`
> 
> https://github.com/laminas/laminas-validator/blob/bbb318490d186821e9488dcbc24455e1578717bb/src/Translator/TranslatorInterface.php#L3-L14
> 
> vs.
> 
> https://github.com/laminas/laminas-i18n/blob/99c7f8a2e1b286db71bee80f39f78b7d3c53d5d1/src/Translator/TranslatorInterface.php#L3-L18

I already noticed

2024-01-13 12:24 UTC, mimmi20 commented
@froschdesign Psalm show this error: `Error: bin/update_hostname_validator.php:152:12: MissingClosureReturnType: Closure does not have a return type, expecting mixed`. Shall I fix this here, or shall this be done in another PR?

2024-01-13 13:16 UTC, froschdesign commented on test/ValidatorPluginManagerTest.php
> +                    [TranslatorInterface::class, true],
The problem with this is that a registered translator of laminas-i18n still cannot be used and a custom factory must also be created and registered.
This is too cumbersome and not user-friendly therefore the goal must be:

- install laminas-validator (using laminas-component-installer)
- install laminas-i18n (using laminas-component-installer)
- install laminas-i18n-resources (using laminas-component-installer)
- register translation files as file patterns for the translator

No need for custom factory or something else.

2024-01-13 13:26 UTC, froschdesign commented
@mimmi20 
I have marked this pull request as a draft in order to find a good and suitable solution.

Thanks for help! 👍🏻

2024-01-13 17:48 UTC, mimmi20 commented on test/ValidatorPluginManagerTest.php
> +                    [TranslatorInterface::class, true],
Please review again

2024-01-25 15:59 UTC, Ocramius requested changes

2024-01-25 15:59 UTC, Ocramius commented on src/Translator/DummyTranslator.php
> +class DummyTranslator implements I18nTranslatorInterface
IMO not for `src/` if it's a dummy 🤔

2024-01-25 17:58 UTC, mimmi20 commented on src/Translator/DummyTranslator.php
> +class DummyTranslator implements I18nTranslatorInterface
This is for the Case when the intl extension is not installed, or the translator is disabled in the configuration. The `MvcTranslator` usus the same logic.

2024-02-05 11:35 UTC, froschdesign commented on src/Translator/DummyTranslator.php
> +class DummyTranslator implements I18nTranslatorInterface
The source folder is correct here because it is used in an application.

By the way, the same can be found in laminas-mvc-i18n: https://github.com/laminas/laminas-mvc-i18n/blob/35fa8706bbc28e78235e488528dc159087493665/src/DummyTranslator.php#L9-L23

2024-05-18 16:21 UTC, froschdesign requested changes
The general process looks good.

I have added some comments to simplify maintenance.

2024-05-18 16:21 UTC, froschdesign commented on src/Translator/DummyTranslator.php
> +class DummyTranslator implements I18nTranslatorInterface
Please mark this class as final, because there is no reason to extend this class.

2024-05-18 16:21 UTC, froschdesign commented on src/Translator/Translator.php
> +class Translator implements
Please mark this class as final, because there is no reason to extend this class.

2024-05-18 16:21 UTC, froschdesign commented on src/Translator/Translator.php
> +    }
In an application or in stand-alone use, there are already other ways to get the translator from laminas-i18n. This method is therefore not necessary.

2024-05-18 16:21 UTC, froschdesign commented on src/Translator/TranslatorFactory.php
> +// phpcs:disable WebimpressCodingStandard.PHP.CorrectClassNameCase
This should not be here. Why is this necessary?

2024-05-18 16:21 UTC, froschdesign commented on src/Translator/TranslatorFactory.php
> +class TranslatorFactory implements FactoryInterface
Please mark this class as final, because there is no reason to extend this class.

2024-05-18 16:21 UTC, froschdesign commented on src/Translator/DummyTranslator.php
> +        return $number == 1 ? $singular : $plural;
Why not type casting?
```suggestion
        return (int) $number === 1 ? $singular : $plural;
```

2024-05-18 16:21 UTC, froschdesign commented on src/Translator/TranslatorFactory.php
> +        }
Is this a planned feature? If not, I would remove it, as the previous and next if statements should be enough.

2024-05-18 17:37 UTC, mimmi20 commented on src/Translator/DummyTranslator.php
> +class DummyTranslator implements I18nTranslatorInterface
done

2024-05-18 17:39 UTC, mimmi20 commented on src/Translator/TranslatorFactory.php
> +class TranslatorFactory implements FactoryInterface
done

2024-05-18 17:46 UTC, mimmi20 commented on src/Translator/Translator.php
> +class Translator implements
done

2024-05-18 17:50 UTC, mimmi20 commented on src/Translator/TranslatorFactory.php
> +        }
see https://github.com/laminas/laminas-mvc-i18n/blob/35fa8706bbc28e78235e488528dc159087493665/src/TranslatorFactory.php#L104-L118

2024-05-18 17:54 UTC, froschdesign commented on src/Translator/TranslatorFactory.php
> +        }
It is also documented in documentation of laminas-mvc-i18n:

https://docs.laminas.dev/laminas-mvc-i18n/services/#mvctranslator-and-translatorfactory

2024-05-18 17:55 UTC, mimmi20 commented on src/Translator/DummyTranslator.php
> +        return $number == 1 ? $singular : $plural;
If I add the typecasting, psalm shows a complaint `RedundantCastGivenDocblockType - src/Translator/DummyTranslator.php:20:16 - Redundant cast to int given docblock-provided type (see https://psalm.dev/263)`

2024-05-18 17:55 UTC, froschdesign commented on src/Translator/TranslatorFactory.php
> +        }
Can stay as it is.

2024-05-18 17:57 UTC, mimmi20 commented on src/Translator/TranslatorFactory.php
> +        }
If this `if` is removed, you can not disable translation if `ext-i18n` is available.

2024-05-18 18:06 UTC, froschdesign commented on src/Translator/DummyTranslator.php
> +        return $number == 1 ? $singular : $plural;
Should be added to `psalm-baseline.xml`. Example can be found in other repositories:

- https://github.com/laminas/laminas-paginator/blob/f9cd4cbc5602e5335cc332f9733d433a94895098/psalm-baseline.xml#L139
- https://github.com/laminas/laminas-paginator/blob/f9cd4cbc5602e5335cc332f9733d433a94895098/psalm-baseline.xml#L206-L214

2024-05-18 18:10 UTC, mimmi20 commented on src/Translator/TranslatorFactory.php
> +// phpcs:disable WebimpressCodingStandard.PHP.CorrectClassNameCase
done

2024-05-18 18:12 UTC, mimmi20 commented on src/Translator/DummyTranslator.php
> +        return $number == 1 ? $singular : $plural;
done

2024-05-18 18:23 UTC, froschdesign commented on test/Translator/TranslatorTest.php
> +    }
The class defines the interfaces and the constructor guarantees the passed translator, so these checks are not useful.

Here are two examples of possible tests:

```suggestion
    public function testTranslate(): void
    {
        $message    = 'This is the message';
        $textDomain = 'default';
        $locale     = 'en_US';

        $this->i18nTranslator->expects($this->once())
                             ->method('translate')
                             ->with($message, $textDomain, $locale)
                             ->willReturn($message);
        $this->assertEquals(
            $message,
            $this->translator->translate(
                $message,
                $textDomain,
                $locale
            )
        );
    }

    public function testTranslatePlural(): void
    {
        $singular   = 'singular';
        $plural     = 'plural';
        $number     = 2;
        $textDomain = 'default';
        $locale     = 'en_US';

        $this->i18nTranslator->expects($this->once())
                             ->method('translatePlural')
                             ->with(
                                 $singular,
                                 $plural,
                                 $number,
                                 $textDomain,
                                 $locale
                             )
                             ->willReturn($singular);
        $this->assertEquals(
            $singular,
            $this->translator->translatePlural(
                $singular,
                $plural,
                $number,
                $textDomain,
                $locale
            )
        );
    }
```

2024-05-18 18:41 UTC, mimmi20 commented on test/Translator/TranslatorTest.php
> +    }
changed

2024-05-21 09:32 UTC, gsteel requested changes
Thanks @mimmi20 - anywhere we can get away with adding native parameter and return types will help with future maintenance on new code 👍

2024-05-21 09:32 UTC, gsteel commented on src/ValidatorPluginManager.php
>          }
```suggestion
        if (! $validator instanceof Translator\TranslatorAwareInterface || ! $container instanceof ContainerInterface) {
            return;
        }
        
        if ($container->has('MvcTranslator')) {
            $validator->setTranslator($container->get('MvcTranslator'));
            
            return;
        }
        
        if ($container->has(TranslatorInterface::class)) {
            $validator->setTranslator($container->get(Translator\TranslatorInterface::class));
        }
```

I think that early returns here make the control flow more readable

2024-05-21 09:32 UTC, gsteel commented on src/Translator/TranslatorFactory.php
> +    {
```suggestion
    public function __invoke(ContainerInterface $container): Translator
    {
```

2024-05-21 09:32 UTC, gsteel commented on src/Translator/TranslatorFactory.php
> +class TranslatorFactory implements FactoryInterface
```suggestion
final class TranslatorFactory
```

Final by default, also, I can't see any reason to implement `FactoryInterface` unless I'm missing something?

2024-05-21 09:32 UTC, gsteel commented on src/Translator/DummyTranslator.php
> +final class DummyTranslator implements I18nTranslatorInterface
```suggestion
/** @internal */
final class DummyTranslator implements I18nTranslatorInterface
```

I'm assuming that this can be marked internal - if it can, it should be.

2024-05-21 09:32 UTC, gsteel commented on src/Translator/Translator.php
> +    public function __construct(protected I18nTranslatorInterface $translator)
```suggestion
    public function __construct(private I18nTranslatorInterface $translator)
```

2024-05-21 09:32 UTC, gsteel commented on src/Translator/TranslatorFactory.php
> +    {
Can we have `null|Translator` as a return type here and explicity return null instead of void where relevant?

2024-05-21 09:32 UTC, gsteel commented on src/Translator/TranslatorFactory.php
> +        }
```suggestion
    private function marshalTranslator(ContainerInterface $container): Translator
    {
        // Load a translator from configuration, if possible
        $translator = $this->marshalTranslatorFromConfig($container);
        if ($translator instanceof Translator) {
            return $translator;
        }
```

2024-05-21 21:24 UTC, gsteel approved these changes
Thank you @mimmi20 👍

2024-05-21 21:27 UTC, gsteel commented
@froschdesign
I'll leave it to you to merge and release if you're happy

2024-06-06 13:21 UTC, gsteel commented
@froschdesign Is this one good to go? LMK and I'll merge and release - then I can cut a 3.0.x branch in the hope that we can get SMv4 happening here soon 🤞

2024-06-12 15:00 UTC, merged