Add `throwExceptions` option to Callback validator
laminas/laminas-validator pull request #242
Opened 2024-05-14 13:38 UTC by gsteel

|    Q          |   A
|-------------- | ------
| BC Break      | no
| New Feature   | yes

### Description

This is a handy option for the callback validator that stops it from swallowing exceptions thrown in your callback. Off by default preserves existing behaviour.

Why? particularly in development, if you have a complex callback, can't figure out why it's failing and step debugging isn't helping you either

The Psalm baseline is mostly improved but there are still issues with the options array - this is mainly because of an `@property array $options` doc block on `AbstractValidator`

2024-05-14 13:52 UTC, Ocramius approved these changes
LGTM, but there is a very mild BC break in `Exception` to `Throwable` behavior change.

I'm fine with this code now suppressing `Throwable` by default, but it should be noted somewhere :thinking:

2024-05-14 13:52 UTC, Ocramius commented on src/Callback.php
> +        } catch (Throwable $error) {
Careful: `Throwable` used to be thrown by default :thinking:

2024-05-14 15:02 UTC, gsteel commented on src/Callback.php
> +        } catch (Throwable $error) {
Ack. I've pushed docs for the option - will this be sufficent do you think?

cc @froschdesign

2024-05-15 13:52 UTC, Xerkus commented on src/Callback.php
> +        } catch (Throwable $error) {
Should validator be swallowing php errors?

2024-05-15 14:48 UTC, gsteel commented on src/Callback.php
> +        } catch (Throwable $error) {
I'd say not, but it's what we have

2024-05-15 17:18 UTC, Xerkus commented on src/Callback.php
> +        } catch (Throwable $error) {
We don't have it. Yet. 
This change will make validator swallow php type errors, calling with fewer parameters or invoking callback that is not callable and such. All the subclasses of Error that I can think of are a direct result of a bug in the code.

2024-05-15 22:15 UTC, gsteel commented on src/Callback.php
> +        } catch (Throwable $error) {
Ah, I see what you mean.

Is this still true considering that `strict_types` is off here?

I think it's probably worth reverting this change anyhow. Ideally, nothing would be caught at all and this whole patch would be unnecessary.

2024-05-16 07:51 UTC, Ocramius commented on src/Callback.php
> +        } catch (Throwable $error) {
I think this breakage is fine BTW, just requires some sort of release notes.

2024-05-16 08:07 UTC, froschdesign requested changes
It's always nice to see that the documentation is also included. 👍🏻 

I have added two small suggestions.

2024-05-16 08:07 UTC, froschdesign commented on docs/book/validators/callback.md
> +## Exceptions within Callbacks
The new option must also be listed at the top of the page:

https://github.com/laminas/laminas-validator/blob/405c711a7a6b75cc00a906bf756324a2599a2ff5/docs/book/validators/callback.md?plain=1#L6-L12

A link to this section would be great.

2024-05-16 08:07 UTC, froschdesign commented on docs/book/validators/callback.md
> +]);
We do not yet have a fixed definition for this but the class with namespace is only used once and all other code examples follow this way:

```suggestion
```php
$callback = static function (mixed $value): bool {
    if ($value === true) {
        return true;
    }
    
    throw new ApplicationException('Bad news');
}

$validator = new Laminas\Validator\Callback([
    'callback' => $callback,
    'throwExceptions' => true,
]);
```

2024-05-16 08:45 UTC, gsteel commented on src/Callback.php
> +        } catch (Throwable $error) {
I've reverted back to `Exception`, you never know, someone out there might be catching `Error` 🤪

With your blessing @Xerkus I'll merge and release.

2024-05-16 08:48 UTC, froschdesign reviewed
LGTM 👍🏻 

I also like the new Psalm type for the options!

2024-05-16 09:56 UTC, Xerkus commented on src/Callback.php
> +        } catch (Throwable $error) {
> Is this still true considering that `strict_types` is off here?

Huh. Unexpected.

Anyway, that leaves catchable errors coming from callback call stack.
I would add inline comment for later however. Something like "Intentionally excluding catchable errors as they are indicative of a bug and should not be suppressed"

My reasoning for allowing errors through is mostly because of user experience. Silly non-fatal mistake in the code can lead to confusing validation failure of a form or when tinkering with input filters. Debugging input filter specification can be daunting even without the error getting suppressed.

2024-05-16 10:14 UTC, Xerkus requested changes
Psalm type declaration needs adjusting

2024-05-16 10:14 UTC, Xerkus commented on src/Callback.php
> + *     callback?: callable|null,
This is wrong for `options` property and it is wrong for `setOptions()` or constructor.
For options property all 3 keys are always defined.
For `setOptions()` this must include AbstractOptions shape from the parent.

2024-05-16 10:14 UTC, Xerkus commented on src/Callback.php
> +     * @var Options
This is _not_ the same as options passed to `setOptions()` or constructor.

2024-05-16 10:14 UTC, Xerkus commented on src/Callback.php
> +    /** @param Options|callable $options */
options here also include generic validator options, so this type info is not entirely correct. See above comment.

2024-05-16 10:14 UTC, Xerkus commented on src/Callback.php
> +        return $this->options['callback'] ?? null;
This change is required because of wrong type declaration for a property.

2024-05-16 10:14 UTC, Xerkus commented on src/Callback.php
> +        return $this->options['callbackOptions'] ?? [];
Same as above

2024-05-16 10:14 UTC, Xerkus commented on src/Callback.php
> +        } catch (Exception $error) {
Minor readability nitpick: rename `$exception` or `$e` as it does not include errors. Add comment for future reference

2024-05-16 10:46 UTC, gsteel commented on src/Callback.php
> + *     callback?: callable|null,
Including all of the abstract options cannot be done without implementing templates thoughout the entire codebase. Psalm does not support intersections on imported types:
https://psalm.dev/r/be51b8b478

Separate shapes for the property vs the argument, fine, but I'm not going to do the work required to get the intersection with AbstractOptions working.

2024-05-16 10:48 UTC, gsteel commented on src/Callback.php
> +    /** @param Options|callable $options */
See https://github.com/laminas/laminas-validator/pull/242#discussion_r1603117308

2024-05-16 10:52 UTC, Xerkus commented on src/Callback.php
> + *     callback?: callable|null,
It is an array shape iirc, so something like this should work: https://psalm.dev/r/be51b8b478

2024-05-16 10:56 UTC, gsteel commented on src/Callback.php
> + *     callback?: callable|null,
I defined the shape on AbstractValidator - It can't be added as an intersection via `@psalm-import-type AbstractOptions from AbstractValidator` because psalm yields `InvalidDocblock` - I have added an intersection with `array<string, mixed>` which is as far as I'm willing to go with this.

2024-05-16 11:10 UTC, Xerkus commented on src/Callback.php
> + * }&array<string, mixed>
property does not need separate type declared imo.

Wouldn't it be preferred to copy options from the parent?

Psalm has unsealed array syntax:
```suggestion
 * @psalm-type OptionsArgument = array{
 *     callback: callable,
 *     callbackOptions?: array<array-key, mixed>,
 *     throwExceptions?: bool,
 *     ...<string, mixed>
 * }
```

2024-05-16 11:12 UTC, Xerkus commented on src/Callback.php
> + *     callback?: callable|null,
I thought psalm supported array unpacking syntax for shapes. Apparently it does not, it is only used for unsealed array feature.

2024-05-16 11:29 UTC, gsteel commented on src/Callback.php
> + * }&array<string, mixed>
The reason I used another type was to make all options optional except for the callable. i.e. `throwExceptions?: bool` instead of `throwExceptions: bool`

2024-05-16 11:31 UTC, Xerkus approved these changes
Unsealed array for options works.

Copying declaration from parent is a maintenance burden for later and changing validators to extend psalm templates is too much effort for this PR.

2024-05-16 11:58 UTC, Xerkus commented
LGTM

2024-05-16 12:03 UTC, merged