Mark all classes as soft `@final` where possible
laminas/laminas-validator pull request #255
Opened 2024-06-12 21:30 UTC by gsteel

To signal intent to make all validators final in v3, this patch adds `@final` to all classes where possible.

2024-06-13 07:58 UTC, froschdesign requested changes

2024-06-13 07:58 UTC, froschdesign commented on src/Uuid.php
> + * @final
This class is already marked as final.

2024-06-13 07:58 UTC, froschdesign commented on src/GpsPoint.php
> +/** @final */
This class is already marked as final.

2024-06-13 07:58 UTC, froschdesign commented on src/IsArray.php
> +/** @final */
This class is already marked as final.

2024-06-13 07:58 UTC, froschdesign commented on src/IsJsonString.php
> + * @final
This class is already marked as final.

2024-06-13 07:58 UTC, froschdesign commented on src/UndisclosedPassword.php
> +/** @final */
This class is already marked as final.

2024-06-13 08:12 UTC, gsteel commented
Thanks @froschdesign 🙏

2024-06-13 09:04 UTC, froschdesign approved these changes
🚢 it!

2024-06-13 09:06 UTC, merged

2024-06-25 08:58 UTC, InvisibleSmiley commented
Some people (like us) extend validators that are now "final" with the intent of either changing the validation failure message (e.g. `InArray::$messageTemplates` to include `%value%` in the message) or creating otherwise pre-configured validators (e.g. by passing fixed values for the `haystack` and `strict` options in an `InArray` constructor override).

The former can alternatively be achieved by passing the `messageTemplates` option to the constructor or calling `setMessage`, but what is the recommended alternative for creating pre-configured validators? I need something that I can reference via FQCN (`::class`) in the end.

AFAICS there is no "abstract validator proxy class" readily available, and I don't want to extend `AbstractValidator` or implement `ValidatorInterface` myself multiple times.

I hope you can clear things up, at the latest when you write the v3 migration.
Until I have a viable alternative for my use case I'll just ignore the added `@final`.

2024-06-25 09:37 UTC, froschdesign commented
@InvisibleSmiley 
> …creating otherwise pre-configured validators…

The options are the key point. Here is one example for an input filter:

```php
[
    'name'       => 'title',
    'required'   => true,
    'filters'    => [
        // …
    ],
    'validators' => [
        [
            'name'    => Laminas\Validator\InArray::class,
            'options' => Example\Validator\Options::INARRAY_FIXED, // Constant in a custom class as an array
        ],
    ],
],
```

2024-06-25 09:38 UTC, gsteel commented
@InvisibleSmiley There are a few ways to handle this, for example composing a validator inside another:

```php
declare(strict_types=1);

namespace LaminasTest\Validator;

use Laminas\ServiceManager\Factory\InvokableFactory;
use Laminas\Validator\InArray;
use Laminas\Validator\ValidatorInterface;

final class ExampleComposedValidator implements ValidatorInterface
{
    private readonly InArray $validator;

    public function __construct()
    {
        $this->validator = new InArray([
            'strict'           => InArray::COMPARE_STRICT,
            'messageTemplates' => [
                InArray::NOT_IN_ARRAY => '%value% not found…',
            ],
        ]);
    }

    public function isValid(mixed $value): bool
    {
        return $this->validator->isValid($value);
    }

    public function getMessages(): array
    {
        return $this->validator->getMessages();
    }
}

$config = [
    'validators' => [
        'factories' => [
            ExampleComposedValidator::class => InvokableFactory::class,
        ],
    ],
];
```

Creating a marker interface and setting up a factory to return whatever validator you need:

```php
interface FirstNameValidator extends ValidatorInterface
{
}

final class FirstNameValidatorFactory
{
    public function __invoke(ContainerInterface $container): ValidatorInterface
    {
        $chain = new ValidatorChain();
        $chain->attachByName(
            NotEmpty::class,
            [
                'messages' => [
                    NotEmpty::IS_EMPTY => 'Oh no!',
                ],
            ],
            true,
        );

        $chain->attachByName(
            Regex::class,
            [
                'pattern' => [
                    '/^Fred/',
                ],
            ],
        );

        return $chain;
    }
}

$config = [
    'validators' => [
        'factories' => [
            FirstNameValidator::class => FirstNameValidatorFactory::class,
        ],
    ],
];
```

You could of course override default implementations with your own factories, such as

```php
$config = [
    'validators' => [
        'factories' => [
            \Laminas\Validator\InArray::class => SomeFactory::class,
        ],
    ],
];
```

Personally, I don't tend to use validator stand-alone, but instead create concrete `InputFilter` instances. For re-usable input specifications, I write invokable classes to represent things in the domain that have specific validation needs such as:

```php
/** @psalm-import-type InputSpecification from InputFilterInterface */
class IataAirportCodeInputSpec
{
    /** @return InputSpecification */
    public function __invoke(bool $required = true): array
    {
        $validators = $required ? [
            'notEmpty' => [
                'name' => NotEmpty::class,
                'options' => [
                    'messages' => [ NotEmpty::IS_EMPTY => 'Please provide an IATA Airport Code' ],
                ],
            ],
            'isCode' => [ 'name' => IataAirportCode::class ],
        ] : [
            'isCode' => [ 'name' => IataAirportCode::class ],
        ];

        return [
            'required' => $required,
            'validators' => $validators,
            'filters' => [
                'trim' => [ 'name' => StringTrim::class ],
                'upper' => [ 'name' => StringToUpper::class ],
                'toNull' => [ 'name' => ToNull::class ],
                'toCode' => [ 'name' => ToIataAirportCode::class ],
            ],
        ];
    }
}

final class AirportInputFilter extends InputFilter
{
    public function init(): void
    {
        $this->add((new IataAirportCodeInputSpec())(true), 'code');
        // ... other inputs ...
    }
}
```

2024-06-25 10:36 UTC, InvisibleSmiley commented
Thanks for the pointers.

I went with the composition approach but such that constructor (parameters) and constants stay compatible with the original. That way it's less of a breaking change.

```php
<?php

declare(strict_types=1);

use Laminas\Stdlib\ArrayUtils;
use Laminas\Validator\InArray;
use Laminas\Validator\ValidatorInterface;
use Traversable;

class MyInArray implements ValidatorInterface
{
    public final const NOT_IN_ARRAY = 'notInArray';

    public final const COMPARE_STRICT = InArray::COMPARE_STRICT;
    public final const COMPARE_NOT_STRICT = InArray::COMPARE_NOT_STRICT;
    public final const COMPARE_NOT_STRICT_AND_PREVENT_STR_TO_INT_VULNERABILITY = InArray::COMPARE_NOT_STRICT_AND_PREVENT_STR_TO_INT_VULNERABILITY;

    private readonly InArray $validator;

    /**
     * @param iterable<string, mixed>|null $options
     */
    public function __construct(?iterable $options = null)
    {
        if ($options instanceof Traversable) {
            $options = ArrayUtils::iteratorToArray($options);
        }

        if (!isset($options['messageTemplates'][self::NOT_IN_ARRAY])) {
            $options['messageTemplates'][self::NOT_IN_ARRAY] = 'The input "%value%" was not found in the haystack';
        }

        $this->validator = new InArray($options);
    }

    public function isValid(mixed $value): bool {
        return $this->validator->isValid($value);
    }

    public function getMessages(): array {
        return $this->validator->getMessages();
    }
}
```