Introduce DateComparison validator
laminas/laminas-validator pull request #275
Opened 2024-06-20 21:34 UTC by gsteel

|    Q          |   A
|-------------- | ------
| Documentation | yes
| New Feature   | yes

### Description

Validates that a date instance or string is between, after or before given boundaries.

Supports standard string formats returned by HTML forms so that validation aligns with W3C spec.

Further ref #272, #274

2024-06-24 13:58 UTC, Ocramius commented on src/DateComparison.php
> + *     inclusive?: bool,
`inclusive` is a bit weird, considering that a `min` and `max` could be different, although it's worked around by instantiating two `DateComparison` validators

2024-06-24 13:58 UTC, Ocramius commented on src/DateComparison.php
> +    }
Overall OK-ish to have this, although I'd just ask the end-user to provide a `DateTimeImmutable` themselves, rather than us trying to infer one :thinking:

2024-06-24 13:58 UTC, Ocramius commented on src/ValidatorPluginManager.php
> +        'DateComparison'         => DateComparison::class,
Is it worth having these short aliases for new classes? We have `::class` since PHP 5.5, so I'd let this go away...

2024-06-24 14:14 UTC, gsteel commented on src/DateComparison.php
> +    }
The main reason I allowed strings - in the specific formats documented, is that I could see how you might generate a validator instance from a form input such as `<input type="date" min="2020-01-01" max="2020-12-31">`, via laminas form for example - requiring a date instance up-front would make this harder.

2024-06-24 14:22 UTC, Ocramius commented on src/DateComparison.php
> +    }
That's fine by me: it's also all tested an such, it's just a lot of complexity added, which is why I raised the question :)

2024-06-24 15:10 UTC, gsteel commented on src/DateComparison.php
> + *     inclusive?: bool,
Do you mean it's weird because you'd want `inclusiveMin` and `inclusiveMax` options rather than just the one option for both?

2024-06-24 15:13 UTC, Ocramius commented on src/DateComparison.php
> + *     inclusive?: bool,
yep, pretty much: since the validator is new, we can do it now.

2024-06-24 15:28 UTC, gsteel commented on src/DateComparison.php
> + *     inclusive?: bool,
Done! Also, thanks for all the reviews today :)

2024-06-24 15:29 UTC, Ocramius commented on src/DateComparison.php
> + *     inclusive?: bool,
> thanks for all the reviews today

Procrastinating work for unpaid work, yay!

2024-06-24 15:30 UTC, Ocramius approved these changes
LGTM, but would like @froschdesign's opinion first :)

2024-06-24 15:30 UTC, gsteel commented on src/DateComparison.php
> + *     inclusive?: bool,
Same!

2024-06-25 11:33 UTC, froschdesign commented on docs/book/v2/validators/date-comparison.md
> +- `inputFormat` _(string)_: Defines the expected date format if required.
```suggestion
| Option         | Data Type                   | Default Value | Description                                                              |
|----------------|-----------------------------|---------------|--------------------------------------------------------------------------|
| `max`          | `string\|DateTimeInterface` | `null`        | Sets the upper bound for the input.                                      |
| `min`          | `string\|DateTimeInterface` | `null`        | Sets the lower bound for the input.                                      |
| `inclusiveMin` | `bool`                      | `true`        | Defines if the validation is inclusive of the lower bound, or exclusive. |
| `inclusiveMax` | `bool`                      | `true`        | Defines if the validation is inclusive of the upper bound, or exclusive. |
| `inputFormat`  | `string`                    | `null`        | Defines the expected date format if required.                            |
```

Output:

| Option         | Data Type                   | Default Value | Description                                                              |
|----------------|-----------------------------|---------------|--------------------------------------------------------------------------|
| `max`          | `string\|DateTimeInterface` | `null`        | Sets the upper bound for the input.                                      |
| `min`          | `string\|DateTimeInterface` | `null`        | Sets the lower bound for the input.                                      |
| `inclusiveMin` | `bool`                      | `true`        | Defines if the validation is inclusive of the lower bound, or exclusive. |
| `inclusiveMax` | `bool`                      | `true`        | Defines if the validation is inclusive of the upper bound, or exclusive. |
| `inputFormat`  | `string`                    | `null`        | Defines the expected date format if required.                            |

@gsteel 
Please recheck the default values. Thanks!

2024-06-25 11:38 UTC, gsteel commented on docs/book/v2/validators/date-comparison.md
> +- `inputFormat` _(string)_: Defines the expected date format if required.
Thanks @froschdesign - Much better!

2024-06-25 11:50 UTC, froschdesign requested changes

2024-06-25 11:50 UTC, froschdesign commented on test/DateComparisonTest.php
> +        ]);
`Bad news` is a string, so the exception message is misleading.

2024-06-25 11:50 UTC, froschdesign commented on test/DateComparisonTest.php
> +        ]);
The same here.

2024-06-25 11:50 UTC, froschdesign commented on test/DateComparisonTest.php
> +        $this->expectExceptionMessage('At least one date boundary must be supplied');
This part is missing in the documentation. Or have I overlooked something?

2024-06-25 12:25 UTC, gsteel commented on test/DateComparisonTest.php
> +        ]);
The test is only matching the first part of the message. The message itself is very clear about the string format required.

2024-06-25 12:26 UTC, gsteel commented on test/DateComparisonTest.php
> +        $this->expectExceptionMessage('At least one date boundary must be supplied');
Added a passage of text to the docs under `Min and Max Date Options`

2024-06-25 12:32 UTC, froschdesign commented on test/DateComparisonTest.php
> +        ]);
I had expected something like: "or a string representation of a date".

2024-06-25 12:34 UTC, gsteel commented on test/DateComparisonTest.php
> +        ]);
The actual message is `Min/max date bounds must be either DateTime instances, or a string in one of the formats: "Y-m-d" for a date or "Y-m-d\TH:i:s" for date time`

2024-06-25 12:34 UTC, gsteel commented on test/DateComparisonTest.php
> +        ]);
`exceptExceptionMessage` is effectively `assertStringContainsString`

2024-06-25 12:51 UTC, froschdesign commented on test/DateComparisonTest.php
> +        ]);
Perfect! 👍🏻

2024-06-25 12:51 UTC, froschdesign approved these changes

2024-06-25 12:56 UTC, gsteel commented
Thank you for the reviews @froschdesign and @Ocramius 👍

2024-06-25 12:56 UTC, merged