Remove the deprecated validators `LessThan`, `GreaterThan` and `Between`
laminas/laminas-validator pull request #290
Opened 2024-06-24 15:59 UTC by gsteel

|    Q          |   A
|-------------- | ------
| BC Break      | yes

### Description

Removes validators deprecated in #276

2024-06-24 16:11 UTC, Ocramius approved these changes

2024-06-25 07:31 UTC, froschdesign requested changes
All removed validators must be listed in the migration guide.

2024-06-25 08:16 UTC, gsteel commented
> All removed validators must be listed in the migration guide.

@froschdesign 

Once I have the replacement validators merged in #275 and #274, I can release 2.60, merge up into 3 and update the #253 with links to the alternative validators

2024-06-25 08:17 UTC, froschdesign approved these changes

2024-06-25 21:03 UTC, merged