Refactor `ValidatorChain`
laminas/laminas-validator pull request #361
Opened 2024-07-11 21:25 UTC by gsteel

|    Q          |   A
|-------------- | ------
| Documentation | yes
| BC Break      | yes
| QA            | yes

### Description

- Adds native parameter and return types
- Drops "fluent" returns from all relevant methods
- Adds optional plugin manager constructor argument - one day we'll get rid of set/get plugin manager…
- Marks `getPluginManager`, `setPluginManager` and `plugin` methods as internal to the \Laminas namespace
- Removed deprecated methods
- Improve test coverage
- Minor changes to the docs such as referencing only validators shipped by this lib (As opposed to I18n) and removing the notice about service manager dependency requirement

2024-07-24 20:05 UTC, froschdesign requested changes

2024-07-24 20:05 UTC, froschdesign commented on src/ValidatorChain.php
> +     * @internal \Laminas
Can we have a better or more meaningful comment here?

2024-07-24 22:25 UTC, gsteel commented on src/ValidatorChain.php
> +     * @internal \Laminas
Yes! Thanks @froschdesign

2024-07-25 07:40 UTC, Ocramius approved these changes

2024-07-25 07:42 UTC, froschdesign commented on src/ValidatorChain.php
> +     * @internal \Laminas
And what is the meaning of `@internal \Laminas`?

2024-07-25 07:47 UTC, gsteel commented on src/ValidatorChain.php
> +     * @internal \Laminas
It scopes internal to a namespace so that, for example, input filter will not get 'internal method' psalm issues

2024-07-25 07:51 UTC, froschdesign commented on src/ValidatorChain.php
> +     * @internal \Laminas
The hint to [Psalm](https://psalm.dev/docs/annotating_code/supported_annotations/#psalm-internal) helps here. Thanks! 👍🏻

2024-07-25 07:51 UTC, froschdesign approved these changes

2024-07-25 08:40 UTC, merged