Introduce `Conditional` validator
laminas/laminas-validator pull request #375
Opened 2024-07-29 22:44 UTC by gsteel

|    Q          |   A
|-------------- | ------
| Documentation | yes
| New Feature   | yes

### Description

Closes #370

2024-07-30 08:19 UTC, froschdesign commented on docs/book/v3/validators/conditional.md
> +`laminas-inputfilter` always passes this parameter to the `isValid` method, but, because it is not part of the `ValidatorInterface` contract, it's documentation has often been overlooked.
This section is important and the parameter is also used in the following classes:

- Callback
- Explode
- Identical
- ValidatorChain

At least for the Callback validator, the section must be adopted, for all others it is internal processing.

See also: #96

2024-07-30 08:29 UTC, froschdesign requested changes

2024-07-30 08:29 UTC, froschdesign commented on docs/book/v3/validators/conditional.md
> +$chainFactory = $container->get(ValidatorChainFactory::class);
We already had this problem in the documentation of laminas-cache, so I propose to show the creation of the container:

```suggestion
$container = new Laminas\Validator\ValidatorPluginManager(
    new Laminas\ServiceManager\ServiceManager()
);
$chainFactory = $container->get(ValidatorChainFactory::class);
```

2024-07-30 22:23 UTC, gsteel commented on docs/book/v3/validators/conditional.md
> +`laminas-inputfilter` always passes this parameter to the `isValid` method, but, because it is not part of the `ValidatorInterface` contract, it's documentation has often been overlooked.
This has been documented in the Callback validator and CreditCard validator which composes a Callback validator in #379 … I'll do a separate patch for the other docs.

2024-07-30 22:32 UTC, gsteel commented on docs/book/v3/validators/conditional.md
> +$chainFactory = $container->get(ValidatorChainFactory::class);
The chain factory is retrieved from the main DI container, not the plugin manger, so I've instantiated it directly in the docs instead.

2024-07-31 07:09 UTC, froschdesign commented on docs/book/v3/validators/conditional.md
> +$chainFactory = $container->get(ValidatorChainFactory::class);
Of course you're absolutely right!

2024-07-31 07:32 UTC, froschdesign approved these changes
LGTM 👍🏻

2024-07-31 08:15 UTC, merged