feat: Add the support for SWIFT Business Identifier Code (BIC) format
laminas/laminas-validator pull request #58
Opened 2020-03-28 17:51 UTC by codisart

|    Q          |   A
|-------------- | ------
| Documentation | yes
| BC Break      | no
| New Feature   | yes

### Description

Implementation proposal for #20

2020-03-29 02:55 UTC, Xerkus commented on docs/book/validators/bic.md
> +the abbreviation for "Business Identifier Code".
Add ISO number defining the BIC. 
Also, I think, historical reference quote would be appropriate here
```suggestion
`Laminas\Validator\BusinessIdentifierCode` validates if a given value could be
a BIC code as defined by ISO 9362:2014. BIC is the abbreviation for "Business
Identifier Code".

> The original scope of ISO 9362 was limited to the identification of banks;
> consequently, the acronym “BIC” was used as an abbreviation for “bank
> identifier code”. The scope has since been extended, in the first place to
> cover all types of financial institutions, and in the 2009 edition, to cover
> non-financial institutions as well.
>
> --- [ISO 9362:2014 Banking — Banking telecommunication messages — Business
> identifier code (BIC)](https://www.iso.org/standard/60390.htm)
```

2020-03-29 13:12 UTC, codisart commented on docs/book/validators/bic.md
> +the abbreviation for "Business Identifier Code".
I applied your suggestion

2020-03-29 20:53 UTC, michalbundyra requested changes
@codisart Thanks a lot for your contribution. I've added some comments.
We need also rebase and target develop as it is new feature and can be released in next minor. Thanks 👍

2020-03-29 20:53 UTC, michalbundyra commented on docs/book/validators/bic.md
> +> The original scope of ISO 9362 was limited to the identification of banks;
I think we need one empty line before blockquote

2020-03-29 20:53 UTC, michalbundyra commented on src/BusinessIdentifierCode.php
> +/**
we need one empty line after php open tag and before file-level doc-block (as PSR-12)

2020-03-29 20:53 UTC, michalbundyra commented on src/BusinessIdentifierCode.php
> +    const NOT_VALID_COUNTRY = 'valueNotCountry';
as we are on PHP 7.1 already we should define visibility for constants

2020-03-29 20:53 UTC, michalbundyra commented on src/BusinessIdentifierCode.php
> +     * @var array
we can be more specific here, either: `string[]` or `array<string, string>`

2020-03-29 20:53 UTC, michalbundyra commented on src/BusinessIdentifierCode.php
> +    public function isValid($value)
as we are on PHP 7.1 we should add return type `: bool` here

2020-03-29 20:53 UTC, michalbundyra commented on src/BusinessIdentifierCode.php
> +    private const REGEX_BIC = '/^[A-Za-z]{4}([A-Za-z]{2})[0-9A-Za-z]{2}([0-9A-Za-z]{3})?$/';
as we accept lowercase and uppercase I think it's better to use `i` modifier, and remove `A-Z` from the regexp.

also: for better readability it would be nice to name the capture group (country), so latter can be used instead of numeric index.

2020-03-29 20:53 UTC, michalbundyra commented on src/BusinessIdentifierCode.php
> +            || !preg_match(self::REGEX_BIC, $value, $matches)
minor: it looks like it's not defined in CS rules for that library but we tend to use single space after `!` operator (as you've done in line 57), the same below please - line 69.

2020-03-29 20:53 UTC, michalbundyra commented on src/BusinessIdentifierCode.php
> +        return in_array($countryCode, self::ISO_COUNTRIES)
It looks like we are missing test cases with lowecase country code (or in general lowercase BIC).
We allow these in regular expression but then we compare them with uppercase country codes.

Also: please add `true` as the 3rd parameter so we have strict type comparison.

Also: do we need separate constant for Kosovo? I see very minor advantage of it, and I am not super convinced to that solution, but I'd like to hear what you think. Thanks.

2020-03-29 20:53 UTC, michalbundyra commented on src/BusinessIdentifierCode.php
> +}
Please add one empty line at the end of the file - it should be reported by CS checks (just noted that somehow CS check is not running on travis for that repo - will fix it shortly) - on local you can run `composer cs-check` to run checks, and `composer cs-fix` to apply some auto-fixes. For more details please see our [CONTRIBUTING guide](https://github.com/laminas/.github/blob/master/CONTRIBUTING.md).

2020-03-29 20:53 UTC, michalbundyra commented on test/BusinessIdentifierCodeTest.php
> +/**
as noted before: please add one empty line after php open tag

2020-03-29 20:53 UTC, michalbundyra commented on test/BusinessIdentifierCodeTest.php
> + * \Laminas\BusinessIdentifierCode
This is wrong, but in general I think we can remove this whole doc-block. No additional value provided here.

2020-03-29 20:53 UTC, michalbundyra commented on test/BusinessIdentifierCodeTest.php
> +            'FEDERATION DES CAISSES DESJARDINS DU QUEBEC, LEVIS, Canada ' => ['CCDQCAMM'],
redundant spaces at the and of the name - here and in couple more cases below.

2020-03-29 20:53 UTC, michalbundyra commented on test/BusinessIdentifierCodeTest.php
> +            'UNICREDIT S.P.A., MILANO, Italy ' => ['UNCRITMM'],
as noted before we are missing any lowercase BIC

2020-03-29 20:53 UTC, michalbundyra commented on test/BusinessIdentifierCodeTest.php
> +    public function testValidateSuccess($code)
we can have type hint `string $code`

2020-03-29 20:53 UTC, michalbundyra commented on test/BusinessIdentifierCodeTest.php
> +    public function NotAStringProvider()
method name should start form lowercase letter, the same for other providers below

2020-03-29 20:53 UTC, michalbundyra commented on test/BusinessIdentifierCodeTest.php
> +        self::assertSame('Invalid type given; string expected', $validator->getMessages()['valueNotString']);
Should we use constant here instead of string `valueNotString` ?
The same in tests below.

2020-03-29 20:53 UTC, michalbundyra commented on test/BusinessIdentifierCodeTest.php
> +}
As noted before: we need one empty line at the end of the file.

2020-03-30 21:36 UTC, codisart commented on src/BusinessIdentifierCode.php
> +        return in_array($countryCode, self::ISO_COUNTRIES)
My tought was to clearly separate the official iso list of the exception. I would even find natural to have an iso country validator.

2020-03-30 21:38 UTC, codisart commented on test/BusinessIdentifierCodeTest.php
> + * \Laminas\BusinessIdentifierCode
Yes it was a bac copy paster

2020-03-30 21:45 UTC, codisart commented on test/BusinessIdentifierCodeTest.php
> +        self::assertSame('Invalid type given; string expected', $validator->getMessages()['valueNotString']);
I have the same discussion with frosch. I think that to use the class constant in this test would add a coupling and would like `Inappropriate Intimacy` smell.

2020-03-30 21:46 UTC, codisart commented on test/BusinessIdentifierCodeTest.php
> +}
added

2020-03-30 21:46 UTC, codisart commented on test/BusinessIdentifierCodeTest.php
> +    public function NotAStringProvider()
changed

2020-03-30 21:47 UTC, codisart commented on test/BusinessIdentifierCodeTest.php
> +    public function testValidateSuccess($code)
added

2020-03-30 21:47 UTC, codisart commented on test/BusinessIdentifierCodeTest.php
> +            'UNICREDIT S.P.A., MILANO, Italy ' => ['UNCRITMM'],
I added some lowercase tests

2020-03-30 21:47 UTC, codisart commented on test/BusinessIdentifierCodeTest.php
> +            'FEDERATION DES CAISSES DESJARDINS DU QUEBEC, LEVIS, Canada ' => ['CCDQCAMM'],
removed

2020-03-30 21:47 UTC, codisart commented on test/BusinessIdentifierCodeTest.php
> +/**
added

2020-03-30 21:48 UTC, codisart commented on src/BusinessIdentifierCode.php
> +}
ran both

2020-03-30 21:48 UTC, codisart commented on src/BusinessIdentifierCode.php
> +            || !preg_match(self::REGEX_BIC, $value, $matches)
added space

2020-03-30 21:48 UTC, codisart commented on src/BusinessIdentifierCode.php
> +    private const REGEX_BIC = '/^[A-Za-z]{4}([A-Za-z]{2})[0-9A-Za-z]{2}([0-9A-Za-z]{3})?$/';
I added the `i` modifier and the named country

2020-03-30 21:49 UTC, codisart commented on src/BusinessIdentifierCode.php
> +    public function isValid($value)
added

2020-03-30 21:49 UTC, codisart commented on src/BusinessIdentifierCode.php
> +     * @var array
added

2020-03-30 21:49 UTC, codisart commented on src/BusinessIdentifierCode.php
> +    const NOT_VALID_COUNTRY = 'valueNotCountry';
added

2020-03-30 21:49 UTC, codisart commented on src/BusinessIdentifierCode.php
> +/**
added

2020-03-30 21:50 UTC, codisart commented on docs/book/validators/bic.md
> +> The original scope of ISO 9362 was limited to the identification of banks;
added

2020-03-30 22:13 UTC, michalbundyra commented on test/BusinessIdentifierCodeTest.php
> +        self::assertSame('Invalid type given; string expected', $validator->getMessages()['valueNotString']);
@froschdesign can you please have a look on that? I think it would be ok to use the constant here, but then we would need the constant to be public. What are your thoughts? Thanks!

2020-03-31 06:21 UTC, froschdesign commented on test/BusinessIdentifierCodeTest.php
> +        self::assertSame('Invalid type given; string expected', $validator->getMessages()['valueNotString']);
All constants must be public because they are used to overwrite the validation messages.

See in the documentation:

> ```php
> use Laminas\Validator\GreaterThan;
> 
> $validator = new GreaterThan();
> $validator->setMessage('Please enter a lower value', GreaterThan::NOT_GREATER);
> ```

https://docs.laminas.dev/laminas-validator/messages/#validation-messages

2020-03-31 07:26 UTC, froschdesign requested changes
Good extension for this component! 👍 

I added some small comments and suggestions.

2020-03-31 07:26 UTC, froschdesign commented on src/BusinessIdentifierCode.php
> +    ];
I think a link to reference (list) would help here.

2020-03-31 07:26 UTC, froschdesign commented on src/BusinessIdentifierCode.php
> +    private const KOSOVO_EXCEPTION = 'XK';
The same here, a link to reference would help.

2020-03-31 07:26 UTC, froschdesign commented on src/BusinessIdentifierCode.php
> +    private const REGEX_BIC = '/^[a-z]{4}(?<country>[a-z]{2})[0-9a-z]{2}([0-9a-z]{3})?$/i';
The same here, if there are an official pattern then a link should be added.

2020-03-31 07:26 UTC, froschdesign commented on docs/book/validators/bic.md
> +# Iban Validator
Wrong name in headline!

2020-03-31 07:26 UTC, froschdesign commented on docs/book/validators/bic.md
> +
```suggestion
`Laminas\Validator\BusinessIdentifierCode` validates if a given value **could be a ["Business Identifier Code" (BIC)](https://www.swift.com/standards/data-standards/bic)** as defined by [ISO 9362](https://wikipedia.org/wiki/ISO_9362).

A BIC is a unique identification code for financial and non-financial institutions.
```

The historical background should not be covered in this documentation, instead a link must be added. The target group of the documentation are the users of the components and therefore the use is in the foreground.

2020-03-31 07:26 UTC, froschdesign commented on docs/book/validators/bic.md
> +BIC codes should be a string which length should be equal to 8 or 11.
```suggestion
BICs should be a string which length should be equal to 8 or 11.
```

Otherwise it means "Business Identifier Code codes". 😉

2020-03-31 07:26 UTC, froschdesign commented on docs/book/validators/bic.md
> +* The last 3 characters are optional and can be letters or digits. It can represent a branche office. The code 'XXX' is often used to represent the ain office when the 11 characters code is used.
Please remove empty lines and reduce the line length. In documentation we follow the coding standard:

> * The soft limit on line length MUST be 120 characters.
> * Lines SHOULD NOT be longer than 80 characters; lines longer than that SHOULD be split into multiple subsequent lines of no more than 80 characters each.

https://www.php-fig.org/psr/psr-12/#23-lines

(https://github.com/laminas/laminas-coding-standard/blob/2.0.0rc1/docs/book/v2/intro.md#laminas-coding-standard)

2020-03-31 07:26 UTC, froschdesign commented on docs/book/validators/bic.md
> +}
```suggestion
if ($validator->isValid('DEUTDEFF')) {
    // Value appears to be valid
}
```

We can use a _real_ example for better demonstration of usage and to allow the example code to be copied.

2020-03-31 11:39 UTC, codisart commented on docs/book/validators/bic.md
> +BIC codes should be a string which length should be equal to 8 or 11.
I have to confess that I have copied the IBAN validator documentation and it use IBAN number. I will change it

2020-03-31 11:50 UTC, codisart commented on docs/book/validators/bic.md
> +}
added a real example

2020-03-31 11:50 UTC, codisart commented on docs/book/validators/bic.md
> +* The last 3 characters are optional and can be letters or digits. It can represent a branche office. The code 'XXX' is often used to represent the ain office when the 11 characters code is used.
applied coding standards

2020-03-31 11:51 UTC, codisart commented on docs/book/validators/bic.md
> +
applied

2020-03-31 11:52 UTC, codisart commented on docs/book/validators/bic.md
> +# Iban Validator
changed

2020-03-31 11:53 UTC, codisart commented on src/BusinessIdentifierCode.php
> +    private const REGEX_BIC = '/^[a-z]{4}(?<country>[a-z]{2})[0-9a-z]{2}([0-9a-z]{3})?$/i';
The pattern is defined in the wikipedia page. Would it be sufficient ?

2020-03-31 11:57 UTC, codisart commented on src/BusinessIdentifierCode.php
> +    ];
added

2020-03-31 11:58 UTC, codisart commented on src/BusinessIdentifierCode.php
> +    private const KOSOVO_EXCEPTION = 'XK';
added

2020-03-31 19:02 UTC, michalbundyra commented on src/BusinessIdentifierCode.php
> +    private const NOT_VALID_COUNTRY = 'valueNotCountry';
As per @froschdesign comment - https://github.com/laminas/laminas-validator/pull/58/files#r400668393 - these constant should be `public` and then we can use them in tests.

2020-04-01 07:56 UTC, froschdesign commented on src/BusinessIdentifierCode.php
> +    private const REGEX_BIC = '/^[a-z]{4}(?<country>[a-z]{2})[0-9a-z]{2}([0-9a-z]{3})?$/i';
If the pattern is adopted, we should add the reference, and if the official specification is behind a paywall, Wikimedia is good.

2020-04-01 07:58 UTC, froschdesign commented on src/BusinessIdentifierCode.php
> +    private const KOSOVO_EXCEPTION = 'XK';
I'm sorry, but I forgot to point out that we use [`@see` for links](https://docs.phpdoc.org/latest/references/phpdoc/tags/see.html).

2020-04-01 19:41 UTC, codisart commented on src/BusinessIdentifierCode.php
> +    private const NOT_VALID_COUNTRY = 'valueNotCountry';
changed

2020-04-11 11:49 UTC, codisart commented
Hello @froschdesign and @michalbundyra, are my last changes ok with your recommendations ?

2020-05-10 20:51 UTC, codisart commented
Hello @froschdesign and @michalbundyra, are there changes needed to this pull request ?

2020-11-18 00:05 UTC, boesing commented on src/BusinessIdentifierCode.php
> +    private const REGEX_BIC = '/^[a-z]{4}(?<country>[a-z]{2})[0-9a-z]{2}([0-9a-z]{3})?$/i';
I've found a regex provided by the "Bundesbank" in this PDF:

https://www.bundesbank.de/resource/blob/749660/d2c6e00664251b4d83483c229e084e44/mL/technische-spezifikationen-scc-anhang-112018-data.pdf

Page 39. Maybe we might use that regex instead or we have a better "official" resource.

2020-11-18 09:01 UTC, codisart commented
Hello @boesing,

I see that you removed the PR from the 2.14 milestone.
What branch should I use to rebase against now ?
What can I do to help to merge this PR ?

2020-11-18 15:01 UTC, boesing commented
@codisart I did not dive very deep into this but there are some change requests in here which will probably block the release of 2.14.0.
As #75 will contain PHP 8 support, I'd like to release this component as far as anything regarding PHP 8 is ready.

After the release, we can re-target this branch to 2.15.
However, as stated [here](https://github.com/laminas/laminas-validator/pull/58#discussion_r525606982), we might want to use official documentation as references when applying RegExp.

2021-01-06 21:22 UTC, weierophinney commented
I updated the REGEX to follow the BundesBank documentation (it was just some minor changes). I also did some cleanup on the documentation.

2021-01-06 21:22 UTC, merged