qa: Replace array by data providers in unit tests
laminas/laminas-validator pull request #62
Opened 2020-05-10 12:24 UTC by codisart

Signed-off-by: codisart <louis.celier@gmail.com>

|    Q          |   A
|-------------- | ------
| QA            | yes

### Description

Replace array for configuration of tests by data providers. 
It allows a better isolation of failing tests

2020-05-11 15:12 UTC, weierophinney requested changes
This is fantastic, and something I've been planning to do for years, but never been able to prioritize!

I've made some notes for additional improvements, which will make the changes you're introducing even more solid. Looking forward to your final results!

2020-05-11 15:12 UTC, weierophinney commented on test/DigitsTest.php
> +            ['abc123',  false],
Can I ask for one further improvement, please? Add _names_ to each of these, to describe the specific behavior:

```php
'invalid; starts with alphabetic chars' => ['abc123', false],
```

and so on.

This helps us identify _specific_ regressions later - and makes it easier to find the test case (and thus the data being tested) when there are failures.

2020-05-11 15:12 UTC, weierophinney commented on test/File/FilesSizeTest.php
> +            [   [['min' => 0, 'max' => 2000]],      true,   true,   false],
With this, and other datasets where you add whitespace around arrays for readability, surround the cases with:

```php
// phpcs:disable
/* add all the various cases */
// phpcs:enable
```

Otherwise, we'll get new phpcs failures, while fixing tests.

2020-05-11 15:12 UTC, weierophinney commented on test/HexTest.php
> +    public function testBasic($input, $expected)
For any test method that is changed to use a data provider, please add `@param` annotations for any non-typehinted arguments.

2020-05-11 19:07 UTC, codisart commented on test/HexTest.php
> +    public function testBasic($input, $expected)
Should I keep the `@return` ?

2020-05-11 21:19 UTC, codisart commented on test/HexTest.php
> +    public function testBasic($input, $expected)
Do the type hinting suffice if it is possible ?

2020-05-11 22:54 UTC, codisart commented on test/DigitsTest.php
> +            ['abc123',  false],
I added for every cases. What do you think about it ?

2020-05-11 22:54 UTC, codisart commented on test/File/FilesSizeTest.php
> +            [   [['min' => 0, 'max' => 2000]],      true,   true,   false],
I added the comments

2021-01-06 15:02 UTC, weierophinney approved these changes

2021-01-06 15:02 UTC, merged