qa: Replace array by data providers in unit tests for the hostname validator
laminas/laminas-validator pull request #63
Opened 2020-05-10 15:54 UTC by codisart

Signed-off-by: codisart <louis.celier@gmail.com>

|    Q          |   A
|-------------- | ------
| QA            | yes

### Description

Replace array for configuration of tests by data providers.
It allows a better isolation of failing tests

2020-05-11 15:16 UTC, weierophinney requested changes
Thanks for these improvements! I've add a couple notes for further improvement; while they're at specific locations, they apply generally to your entire patch.

2020-05-11 15:16 UTC, weierophinney commented on test/HostnameTest.php
> +    public function testBasic($option, $expected, $inputValues)
Please add `@param` annotations for these new arguments.

2020-05-11 15:16 UTC, weierophinney commented on test/HostnameTest.php
>              [Hostname::ALLOW_IP, true, ['1.2.3.4', '10.0.0.1', '255.255.255.255']],
I'd argue that you should split these out, so we can have failures rise for each of the IP/hostname arguments; that will allow us to identify specific recursions later more easily.

Additionally, provide names for each case:

```php
'allow-ip succeeds for 1.2.3.4' => [Hostname::ALLOW_IP, true, '1.2.3.4'],
```

As noted in a PR you've made against laminas-validator, this helps us identify specific data sets more easily when they fail.

2020-10-01 22:48 UTC, codisart commented on test/HostnameTest.php
> +    public function testBasic($option, $expected, $inputValues)
I have added the annotations

2020-10-01 22:49 UTC, codisart commented on test/HostnameTest.php
>              [Hostname::ALLOW_IP, true, ['1.2.3.4', '10.0.0.1', '255.255.255.255']],
I have added the keys and separated the test cases

2021-01-06 19:50 UTC, merged