Upgrading to PHP 8
laminas/laminas-validator pull request #75
Opened 2020-10-05 19:14 UTC by jfernancordova

|    Q          |   A
|-------------- | ------
| New Feature   | yes

### Description

- [x] Modify composer.json to provide support for PHP 8.0 by adding the constraint ~8.0.0
- [x]  Modify composer.json to drop support for PHP less than 7.3
- [x] Modify composer.json to implement phpunit 9.3 which supports PHP 7.3+
- [x] Modify .travis.yml to ignore platform requirements when installing composer dependencies (simply add --ignore-platform-reqs to COMPOSER_ARGS env variable)
- [ ] Modify .travis.yml to add PHP 8.0 to the matrix (NOTE: Do not allow failures as PHP 8.0 has a feature freeze since 2020-08-04!)
- [ ] Modify source code in case there are incompatibilities with PHP 8.0

2020-10-05 19:36 UTC, boesing requested changes

2020-10-05 19:36 UTC, boesing commented on composer.json
> +        "php": "~8.0.0",
Please use `^7.3 || ~8.0.0` as descripted in #74

2020-10-05 19:36 UTC, boesing commented on composer.json
> +        "phpunit/phpunit": "^9.3.*",
Its okay to use `^9.3` here

2020-10-05 19:36 UTC, boesing commented on .travis.yml
> +    - COMPOSER_ARGS="--ignore-platform-reqs --no-interaction"
please only ignore platform requirements for nightly (which is not yet part of this file)

2020-10-05 19:43 UTC, jfernancordova commented on composer.json
> +        "php": "~8.0.0",
Fixed

2020-10-05 19:43 UTC, jfernancordova commented on composer.json
> +        "phpunit/phpunit": "^9.3.*",
Fixed

2020-10-05 19:43 UTC, jfernancordova commented on .travis.yml
> +    - COMPOSER_ARGS="--ignore-platform-reqs --no-interaction"
Ok, I get it, I'll revert this

2020-10-05 19:45 UTC, jfernancordova commented
@boesing I just added PHP 8.0 to the matrix in travis.yml, anything else?

2020-10-05 19:46 UTC, boesing commented
> @boesing I just added PHP 8.0 to the matrix in travis.yml, anything else?

You have to use `nightly` in travis as there is no `8.0` version available yet.
After this, you can convert your PR to `Ready for review` by yourself and then we'll see what travis says 👍

2020-10-05 19:54 UTC, jfernancordova commented
Perfect

2020-10-05 20:16 UTC, boesing commented
@jfernancordova Please check mezzio/mezzio-cors [.travis.yml](https://github.com/mezzio/mezzio-cors/blob/1.1.x/.travis.yml) to see how you have to change the `.travis.yml` to finish this PR. Just ignore the `allow_failures` part as this is fixed in a PR in that repository.

2020-10-05 20:38 UTC, boesing requested changes
Please remove PHP <7.3 from travis aswell.

2020-10-05 21:09 UTC, jfernancordova commented
@boesing it's failing for **_laminas/laminas-uri_**, do you think that upgrading this dependency, could it solve this error in travis?

2020-10-06 02:57 UTC, glensc commented
`--ignore-platform-reqs` should never be used. it does not just ignore `ext-foo` requirement, but also PHP version dependency installing packages that are not compatible at all with the runtime. for example running in 5.6 installing package resolving that requires PHP 7.1 and then execution results fatal errors due invalid syntax. 

if you don't have ext-foo installed, fake it with local `composer config platform.ext-foo '0'` instead.

example:
- https://github.com/eventum/eventum/blob/v3.9.0/bin/releng/configure.sh#L11-L13

2020-10-06 16:18 UTC, boesing commented
> `--ignore-platform-reqs` should never be used. it does not just ignore `ext-foo` requirement, but also PHP version dependency installing packages that are not compatible at all with the runtime. for example running in 5.6 installing package resolving that requires PHP 7.1 and then execution results fatal errors due invalid syntax.
> 
> if you don't have ext-foo installed, fake it with local `composer config platform.ext-foo '0'` instead.
 
Thanks for the information.
You are right, its not a good solution. However, this is the only way to initially provide PHP 8.0 support on packages. Since we are not using `composer v2` which wont happen in the near future anyways, there is no way to use `--ignore-platform-req=php` and thus, we *have* to use `--ignore-platform-reqs`. Without ignoring platform reqs, this package is not testable by travis.
However, this should not be used in upstream projects but for travis this is absolutely fine.

2020-10-06 16:19 UTC, boesing requested changes

2020-10-06 16:19 UTC, boesing commented on .travis.yml
> +    - COMPOSER_ARGS="--no-interaction --ignore-platform-reqs"
Please only ignore platform reqs for nightly builds

2020-10-06 17:28 UTC, jfernancordova commented on .travis.yml
> +    - COMPOSER_ARGS="--no-interaction --ignore-platform-reqs"
Fixed

2020-10-07 08:35 UTC, glensc commented
> we have to use `--ignore-platform-reqs`. 

that is incorrect. what is the error you trying to avoid with the flag?

2020-10-11 20:14 UTC, boesing commented
> > we have to use `--ignore-platform-reqs`.
> 
> that is incorrect. what is the error you trying to avoid with the flag?

I want to avoid having trouble with 3rd-party composer dependencies which are not yet PHP 8.0 compatible as no dependency wont install when one of them are not compatible (yet).

Lets take `laminas/laminas-uri` for example. You wont be able to use `composer install` unless you either provide `--ignore-platform-reqs` (to ignore that the package is not yet compatible with PHP 8.0) or by using `--no-dev`.

Feel free to resolve dependency tree on PHP 8.0 without passing `--ignore-platform-reqs`.

2020-10-11 20:31 UTC, boesing commented
@jfernancordova As you can see, the tests are still failing. This is due to the fact that there are some strange circulare dependencies going on in this package.

Please run `composer test` locally. You will see several problems which needs to get fixed (as there are missing methods such as `assertAttributeSame` and deprecations for prophecy).

You can use `phpspec/prophecy-phpunit` as a dev dependency and add the trait to the tests which are using the `prophesize` method.
To resolve dependencies, you can temporarily add `"version": "2.14.0",` to the `composer.json` (but please do not commit that as this is only needed locally). When you've added `phpspec/prophecy-phpunit` you can remove the `version` property from `composer.json` as the dependency tree should be resolved locally.

@Ocramius @weierophinney Any ideas how to solve such circular dependencies in the future? Is there a way of adding the `version` property to `composer.json` from within the `automatic-releases`?

2020-10-11 20:37 UTC, jfernancordova commented
> @jfernancordova As you can see, the tests are still failing. This is due to the fact that there are some strange circulare dependencies going on in this package.
> 
> Please run `composer test` locally. You will see several problems which needs to get fixed (as there are missing methods such as `assertAttributeSame` and deprecations for prophecy).
> 
> You can use `phpspec/prophecy-phpunit` as a dev dependency and add the trait to the tests which are using the `prophesize` method.
> To resolve dependencies, you can temporarily add `"version": "2.14.0",` to the `composer.json` (but please do not commit that as this is only needed locally). When you've added `phpspec/prophecy-phpunit` you can remove the `version` property from `composer.json` as the dependency tree should be resolved locally.
> 
> @Ocramius @weierophinney Any ideas how to solve such circular dependencies in the future? Is there a way of adding the `version` property to `composer.json` from within the `automatic-releases`?

Ok. let me check.

2020-10-11 22:28 UTC, jfernancordova commented
@boesing, I fixed all tests and executed `composer test` locally, however, I'm seeing the Build from travis CI, and other dependencies such as: laminas/laminas-http are not working with laminas/laminas-validator, can you suggest any solution for this?, thx

2020-10-16 15:55 UTC, boesing commented
@jfernancordova You can add `"version": "2.14.0"` to `composer.json` in a single commit. 
After that, push to your branch. Let travis do its job. 
- When everything is green, *hooray*. Copy the link to the test-results and paste them in here.
- If not, try to determine the problems and fix them and post the link to the green test-results here.

When done, drop the commit from history and force-push back to your branch 👍 

Not sure if there is a better way but thats what comes to my mind.

2020-10-16 20:55 UTC, jfernancordova commented
> @jfernancordova You can add `"version": "2.14.0"` to `composer.json` in a single commit.
> After that, push to your branch. Let travis do its job.
> 
>     * When everything is green, _hooray_. Copy the link to the test-results and paste them in here.
> 
>     * If not, try to determine the problems and fix them and post the link to the green test-results here.
> 
> 
> When done, drop the commit from history and force-push back to your branch +1
> 
> Not sure if there is a better way but thats what comes to my mind.

Hi @boesing, this is the link: https://travis-ci.com/github/laminas/laminas-validator/builds/190545033, I hope it's ok.

2020-10-28 20:09 UTC, jfernancordova commented
@boesing what do you think?, I just changed some code and fixed all tests, anything else?

2020-10-28 20:26 UTC, froschdesign commented on test/Db/NoRecordExistsTest.php
> +        if (explode('.', PHP_VERSION)[0] >= 8.0) {
[PHP's `version_compare`](https://www.php.net/manual/function.version-compare.php) can be used here.

2020-10-28 20:26 UTC, froschdesign commented on test/Db/NoRecordExistsTest.php
> +        if (explode('.', PHP_VERSION)[0] >= 8.0) {
The same here and so on…

2020-10-28 20:32 UTC, froschdesign commented on test/InArrayTest.php
> +        $this->assertFalse($validator->isValid('A'));
This means a change of logic. This cannot be correct and should be checked again.

2020-10-28 20:34 UTC, froschdesign commented on test/InArrayTest.php
> +        $this->assertFalse($validator->isValid(0));
The same here. The haystack contains the following values:

https://github.com/laminas/laminas-validator/blob/83c2a967cd823a76a81589e895363aac73b4d646/test/InArrayTest.php#L133-L137

2020-10-28 20:44 UTC, jfernancordova commented on test/Db/NoRecordExistsTest.php
> +        if (explode('.', PHP_VERSION)[0] >= 8.0) {
Great, I'll fix these conditionals, thx.

2020-10-28 20:46 UTC, jfernancordova commented on test/InArrayTest.php
> +        $this->assertFalse($validator->isValid('A'));
You're, I will check this.

2020-10-28 20:49 UTC, froschdesign commented on test/ValidatorPluginManagerFactoryTest.php
> +            $this->assertObjectHasAttribute('creationContext', $validators);
This section is no longer useful and testing internal implementation details is the wrong way.

2020-10-29 06:51 UTC, froschdesign commented on src/InArray.php
> +                    }elseif (InArray::COMPARE_NOT_STRICT == $this->strict){
If you find a problem in this the validator independent of the PHP 8 support then create a separate pull request with an unit test. Otherwise, please revert the changes in this file.  Thanks!

2020-10-29 11:10 UTC, glensc commented on test/Db/NoRecordExistsTest.php
> +        if (explode('.', PHP_VERSION)[0] >= 8.0) {
if you are comparing the php version, use PHP_VERSION_ID constant

2020-10-29 11:12 UTC, glensc commented on test/Db/NoRecordExistsTest.php
> +        if (explode('.', PHP_VERSION)[0] >= 8.0) {
altho, you should use the requires annotation here instead:


```
     * @requires PHP < 8.0
```

- https://phpunit.readthedocs.io/en/9.3/incomplete-and-skipped-tests.html#skipping-tests-using-requires

2020-10-29 11:48 UTC, jfernancordova commented on test/Db/NoRecordExistsTest.php
> +        if (explode('.', PHP_VERSION)[0] >= 8.0) {
Great, thank you @glensc!

2020-10-29 12:22 UTC, jfernancordova commented on test/ValidatorPluginManagerFactoryTest.php
> +            $this->assertObjectHasAttribute('creationContext', $validators);
Ok, I'll remove the condition

2020-10-29 12:23 UTC, jfernancordova commented on src/InArray.php
> +                    }elseif (InArray::COMPARE_NOT_STRICT == $this->strict){
Ok, I revert this change and add a version compare in the test, because only 2 or 3 cases are not working with PHP 8.0

2020-10-29 13:01 UTC, froschdesign commented on src/InArray.php
> +                    }elseif (InArray::COMPARE_NOT_STRICT == $this->strict){
@jfernancordova
> …add a version compare in the test, because only 2 or 3 cases are not working with PHP 8.0.

I am afraid there is a misunderstanding here. Sorry!
All cases must be passed otherwise it would be a break of the behaviour. The validator must produce the same results in all PHP versions.

2020-10-29 13:15 UTC, jfernancordova commented on src/InArray.php
> +                    }elseif (InArray::COMPARE_NOT_STRICT == $this->strict){
I see, ok.

2020-10-29 13:18 UTC, froschdesign commented on src/InArray.php
> +                    }elseif (InArray::COMPARE_NOT_STRICT == $this->strict){
Thanks in advance! 👍 👍 👍

2020-10-29 14:47 UTC, jfernancordova commented
@froschdesign I analyzed the code again. I could understand the complexity, so I did a refactor in which the code is cleaner now. What do you think?. Any suggestions are welcome.

2020-10-31 12:34 UTC, boesing requested changes

2020-10-31 12:34 UTC, boesing commented on src/AbstractValidator.php
> +            if (($name !== 'setOptions') && get_parent_class($this) && method_exists($this, $name)) {
Could you explain why you've added these additional checks with `get_parent_class`?
As this is an abstract class, this check is *always* true or do I miss something here?

In case we do not need this additional check (and I think so), please revert this change.

2020-10-31 12:34 UTC, boesing commented on src/InArray.php
> +        $rv = array_filter($array, 'is_array');
depending on the size of the given array, you might want to use `foreach` with early return instead. This will avoid unnecessary CPU cycles.

2020-10-31 12:34 UTC, boesing commented on src/InArray.php
> +    private function isMultiArray($array)
Please also add proper typehints to the methods parameter and return value.

2020-10-31 13:09 UTC, jfernancordova commented on src/AbstractValidator.php
> +            if (($name !== 'setOptions') && get_parent_class($this) && method_exists($this, $name)) {
Yes, I just consider add an extra validation, but you're right, I'm going to revert this change.

2020-10-31 13:46 UTC, boesing requested changes

2020-10-31 13:46 UTC, boesing commented on .travis.yml
> -        - EXECUTE_HOSTNAME_CHECK=true
Oh, as far as I can see here, we dropped some checks.
Could you re-add these to PHP 7.4?
Sorry, realized just yet.
After this, we should be good to go (I think the CS check will find some problems, maybe you check yourself by locally executing `composer cs-check`).

2020-10-31 13:48 UTC, jfernancordova commented on .travis.yml
> -        - EXECUTE_HOSTNAME_CHECK=true
No problem!

2020-10-31 20:13 UTC, boesing requested changes

2020-10-31 20:13 UTC, boesing commented on .travis.yml
> +        - EXECUTE_HOSTNAME_CHECK=true
`TEST_COVERAGE` and `CS_CHECK` are missing in here aswell.

2020-11-01 00:12 UTC, jfernancordova commented on .travis.yml
> +        - EXECUTE_HOSTNAME_CHECK=true
Uh, I'll add them too, sorry.

2020-11-01 00:29 UTC, jfernancordova commented
@boesing Adding `TEST_COVERAGE` is returning an error like: `PHP Fatal error:  Uncaught Error: Maximum function nesting level of '256' reached, aborting! in /home/travis/build/laminas/laminas-validator/vendor/nikic/php-parser/lib/PhpParser/NodeAbstract.php`. I think it's about of `php.ini` configuration file.

2020-11-01 00:50 UTC, jfernancordova commented on .travis.yml
> +        - EXECUTE_HOSTNAME_CHECK=true
@boesing Adding TEST_COVERAGE is returning an error: PHP Fatal error: Uncaught Error: Maximum function nesting level of '256' reached, aborting! in /home/travis/build/laminas/laminas-validator/vendor/nikic/php-parser/lib/PhpParser/NodeAbstract.php. I think it's about of php.ini configuration file.

2020-11-02 21:36 UTC, boesing requested changes

2020-11-02 21:36 UTC, boesing commented on .travis.yml
> +  - echo xdebug.max_nesting_level = 3000 >> $INI
Does this happen for coverage only? 
I'd prefer having this within `phpunit.xml.dist` instead as its phpunit related and could be a problem in local development aswell.

See phpunit configuration documentation: https://phpunit.readthedocs.io/en/9.3/configuration.html#the-ini-element

2020-11-02 21:36 UTC, boesing commented on composer.json
> +    "version": "2.14.0",
after tests are green, please remove this from the `composer.json` by removing the related commit.

2020-11-03 00:12 UTC, jfernancordova commented on .travis.yml
> +  - echo xdebug.max_nesting_level = 3000 >> $INI
Yes, only for coverage, ok, I'll check about it.

2020-11-03 00:12 UTC, jfernancordova commented on composer.json
> +    "version": "2.14.0",
Ok

2020-11-03 00:27 UTC, jfernancordova commented
@boesing Before removing the composer's version, all tests are green!
https://travis-ci.com/github/laminas/laminas-validator/builds/197589684

2020-11-17 23:47 UTC, boesing approved these changes
LGTM

2020-12-29 19:37 UTC, samsonasik commented
please update laminas-http require-dev to ^2.14

2020-12-29 20:06 UTC, jfernancordova commented
> please update laminas-http require-dev to ^2.14

Ok!

2020-12-31 04:12 UTC, Ocramius requested changes
We really can't use `@requires php<8` for releasing this: if it doesn't run, it isn't ready 😞

2020-12-31 04:12 UTC, Ocramius commented on src/InArray.php
> +                if (! $this->isMultiArray($haystack) && array_key_exists($value, array_flip($haystack))) {
Is flipping safe here? What of the array contains objects?

2020-12-31 04:12 UTC, Ocramius commented on src/InArray.php
> +            if (array_search($value, $haystack, self::COMPARE_STRICT == $this->strict)) {
Can `==` and `!=` be replaced with strict comparison (and is it safe to do so)?

2020-12-31 04:12 UTC, Ocramius commented on src/InArray.php
> +    private function isMultiArray(array $array): bool
s/multi/multidimensional?

2020-12-31 04:12 UTC, Ocramius commented on test/Db/NoRecordExistsTest.php
> +     * For PHP 8.0 Library laminas/laminas-stdlib/src/ArrayUtils.php needs to be upgraded
This means that we aren't yet php8-compatible, and we should fix that dependency (bug) first

2020-12-31 04:12 UTC, Ocramius commented on test/Db/NoRecordExistsTest.php
> +     * @requires PHP < 8.0
This means that we aren't yet php8-compatible, and we should fix that dependency (bug) first

2020-12-31 10:28 UTC, froschdesign commented on .travis.yml
> +    - php: nightly
Version 8.0 should be used here.

2020-12-31 11:33 UTC, jfernancordova commented on src/InArray.php
> +                if (! $this->isMultiArray($haystack) && array_key_exists($value, array_flip($haystack))) {
Hi @Ocramius, it was the solution I thought could work and all tests passed: https://travis-ci.com/github/laminas/laminas-validator/builds/197589684, unfortunately, the last implementation breaks with PHP 8, if you have any suggestions, let me know, please!

However, I could reevaluate it!

2020-12-31 11:50 UTC, jfernancordova commented on src/InArray.php
> +            if (array_search($value, $haystack, self::COMPARE_STRICT == $this->strict)) {
Sorry @Ocramius, I don't understand you, do you want to replace it with strict comparison or know if it safe?

2020-12-31 11:53 UTC, jfernancordova commented on src/InArray.php
> +    private function isMultiArray(array $array): bool
yes multidimensional!

2020-12-31 11:53 UTC, jfernancordova commented on test/Db/NoRecordExistsTest.php
> +     * For PHP 8.0 Library laminas/laminas-stdlib/src/ArrayUtils.php needs to be upgraded
That's right!

2020-12-31 11:53 UTC, jfernancordova commented on test/Db/NoRecordExistsTest.php
> +     * @requires PHP < 8.0
That's right!

2020-12-31 12:04 UTC, glensc commented on src/InArray.php
> +    private function isMultiArray(array $array): bool
@richardjennings @Ocramius suggested here you to change the word `multi` with `multidimensional`

2020-12-31 12:06 UTC, glensc commented on src/InArray.php
> +            if (array_search($value, $haystack, self::COMPARE_STRICT == $this->strict)) {
@jfernancordova, I read it as to make a change to do strict compare but validate first is the change legal first, i.e not introducing a bug by making such change.

2020-12-31 12:06 UTC, jfernancordova commented on src/InArray.php
> +    private function isMultiArray(array $array): bool
I get it now, thanks @glensc!

2021-01-01 18:27 UTC, jfernancordova commented on src/InArray.php
> +                if (! $this->isMultiArray($haystack) && array_key_exists($value, array_flip($haystack))) {
I'm working with this validation!

2021-01-01 18:28 UTC, Ocramius requested changes

2021-01-01 18:28 UTC, Ocramius commented on .travis.yml
> +    - php: nightly
If we test nightly, we should probably allow failures there (it's very unstable)

2021-01-01 18:28 UTC, Ocramius commented on test/ValidatorPluginManagerFactoryTest.php
> -        if (method_exists($validators, 'configure')) {
Ìsn't v3 "current"?

2021-01-01 18:37 UTC, jfernancordova commented on src/InArray.php
> +                if (! $this->isMultiArray($haystack) && array_key_exists($value, array_flip($haystack))) {
@Ocramius what do you think about this?
```
$haystack = is_object($haystack) ? get_object_vars($haystack) : $haystack;
if (! $this->isMultidimensionalArray($haystack) && array_key_exists($value, array_flip($haystack))) {
    return true;
}
```

2021-01-01 20:26 UTC, jfernancordova commented on .travis.yml
> +    - php: nightly
so I remove nightly, right?

2021-01-01 20:30 UTC, samsonasik commented on .travis.yml
> +    - php: nightly
iirc, nightly was for php 8 dev, I think it can be removed.

2021-01-01 20:48 UTC, jfernancordova commented on test/ValidatorPluginManagerFactoryTest.php
> -        if (method_exists($validators, 'configure')) {
@Ocramius I tried to set these asserts, especially v3, and they're deprecated, that's why I remove this block.

2021-01-01 20:48 UTC, jfernancordova commented on .travis.yml
> +    - php: nightly
OK!

2021-01-04 12:23 UTC, lahivee commented
Hey guys, is there any way to push this through donations? We are depending on this package to support PHP8 for this package: https://github.com/beyondcode/expose/pull/163

2021-01-05 08:30 UTC, danmichaelo commented
Per https://github.com/laminas/laminas-validator/pull/79#discussion_r550776411 , can we remove `laminas/laminas-cache` as a dev dependency? Couldn't find a single reference to caches in this repo: `find . -iname '*.php' -exec grep -i 'Cache' {} \;`

2021-01-05 22:02 UTC, weierophinney requested changes
There are a lot of CS changes that are (a) unrelated to updating to PHP 8, and (b) incorrect by our coding standards. Additionally, the InArray validator has a number of changes outside the scope of the PR (adding PHP 8 support), and without new tests to validate the new functionality.

Please run `composer cs-fix`, then `composer cs-check`, fixing and committing any changes needed to make the checks pass. Also, please back out the changes in the `InArray` validator; if you want to see them in a future version, please submit them as a separate PR, with tests demonstrating and validating the changes.

2021-01-05 22:02 UTC, weierophinney commented on composer.json
> +        "laminas/laminas-http": "^2.14",
Bump to 2.14.2, please

2021-01-05 22:02 UTC, weierophinney commented on src/InArray.php
>          }
These changes are all unrelated... and I suspect you ran a CS tool over this other than our own `composer cs-check` and `composer cs-fix` (which use phpcs and the laminas-coding-standard). Please either revert these changes, or run `composer cs-fix` and commit the updates.

2021-01-05 22:02 UTC, weierophinney commented on src/InArray.php
> +                    if (self::COMPARE_NOT_STRICT == $this->strict) {
What is this change for, exactly? It seems unrelated to the bump to PHP 8...

2021-01-05 22:02 UTC, weierophinney commented on src/InArray.php
> +            if (array_search($value, $haystack, self::COMPARE_STRICT == $this->strict)) {
Please revert this change; they are not semantically the same!

We want to see if the value is in the array, not return the first match. `in_array()` is the correct one to use here.

2021-01-05 22:02 UTC, weierophinney commented on src/InArray.php
> +    private function isArrayKeyExists(string $key, array $haystack): bool
This is misnamed, and duplicates the functionality of `in_array()`. Please remove, and replace calls to this method with `in_array($value, $haystack)`.

2021-01-05 22:02 UTC, weierophinney commented on src/InArray.php
> +                if (! $this->isMultidimensionalArray($haystack) && $this->isArrayKeyExists($value, $haystack)) {
This is unrelated to updating to PHP 8. Please remove.

2021-01-05 22:27 UTC, jfernancordova commented
Hi @weierophinney, As you can see, reverting the changes from inArray.php class, break the tests with PHP 8.0, https://travis-ci.com/github/laminas/laminas-validator/jobs/468944524, that's why I changed the code, the native function in_array seems not working as the previous version!

2021-01-05 22:27 UTC, jfernancordova commented on src/InArray.php
>          }
Ok!

2021-01-06 08:44 UTC, lahivee commented
@jfernancordova thank you so much for your work on this!

2021-01-06 14:39 UTC, weierophinney commented
@jfernancordova —

> reverting the changes from inArray.php class, break the tests with PHP 8.0, https://travis-ci.com/github/laminas/laminas-validator/jobs/468944524, that's why I changed the code, the native function in_array seems not working as the previous versions.
> 
> However, I'm going to create another PR with the new changes and their tests for inArray validator.

I'm fine with including the changes here; in fact, since the PHP 8 tests _fail_ without them, then we need them before merging. I just didn't understand why you weren't using `in_array()` directly, and there were no comments in the code to indicate why.

Speaking of: it may be good to create a bug on bugs.php.net about this. The PHP 8 changelog does not mention anything about the change in behavior, and I don't see any bugs currently filed around it.

2021-01-06 14:50 UTC, jfernancordova commented
> @jfernancordova —
> 
> > reverting the changes from inArray.php class, break the tests with PHP 8.0, https://travis-ci.com/github/laminas/laminas-validator/jobs/468944524, that's why I changed the code, the native function in_array seems not working as the previous versions.
> > However, I'm going to create another PR with the new changes and their tests for inArray validator.
> 
> I'm fine with including the changes here; in fact, since the PHP 8 tests _fail_ without them, then we need them before merging. I just didn't understand why you weren't using `in_array()` directly, and there were no comments in the code to indicate why.
> 
> Speaking of: it may be good to create a bug on bugs.php.net about this. The PHP 8 changelog does not mention anything about the change in behavior, and I don't see any bugs currently filed around it.

You're right, I did not explain why I removed the code, especially why I did not use the `in_array()` function.
Would you like me to fix InArray validator class adding why I don't use the `in_array()` in this PR?
It would be the same before reverting the requested changes.

2021-01-06 14:52 UTC, weierophinney commented
> Would you like me to fix InArray validator class adding why I don't use the `in_array()` in this PR?
> It would be the same before reverting the requested changes.

Yes, please!

2021-01-06 17:57 UTC, jfernancordova commented
Hi again @weierophinney! I started to modify the inArray validator, I realized that I did not need some functions I added, just changed the way of conditionals and using `in_array()` function, I ask you again if you want to explain this way but I think it is implicit.

2021-01-06 18:51 UTC, weierophinney commented on src/InArray.php
>              }
This part (and the related comparison in the recursive comparison section)... seems wrong. You're testing to see if a constant value referencing "not strict comparisons" matches the  flag provided by the consumer as to whether or not to do strict comparisons. You're not comparing the value **at all**, and yet if these match, you're returning true.

At best, this is only **accidentally** causing tests to pass. At worse, it's hiding something else.

So, I did some digging, and had quite a surprise: The behavior of `==` appears to have changed in PHP 8.

I did the following:

```php
$values = ['test', 0, 'A', 0.0, 'foo', 1, 'a', 'c'];
foreach ($values as $value) {
    printf("- Is b equal to %s?\t%s\n", $value, 'b' == $value ? 'Yes' : 'No');
}
```

Under PHP 7 versions, you get the following output:

```text
- Is b equal to test?	No
- Is b equal to 0?	Yes
- Is b equal to A?	No
- Is b equal to 0?	Yes
- Is b equal to foo?	No
- Is b equal to 1?	No
- Is b equal to a?	No
- Is b equal to c?	No
```

However, under PHP 8, we get:

```text
- Is b equal to test?	No
- Is b equal to 0?	No
- Is b equal to A?	No
- Is b equal to 0?	No
- Is b equal to foo?	No
- Is b equal to 1?	No
- Is b equal to a?	No
- Is b equal to c?	No
```

This is true even with strict_types off. And, obviously, this is hugely problematic for this particular comparison.

Looking in the [PHP 8 upgrade guide](https://github.com/php/php-src/blob/PHP-8.0/UPGRADING), there is a note about this:

> Non-strict comparisons between numbers and non-numeric strings now work by casting the number to string and comparing the strings. Comparisons between numbers and numeric strings continue to work as before. Notably, this means that `0 == "not-a-number"` is considered false now.

As such, I'm going to update the tests to vary the assertions based on PHP version, and I'll push the changes back to your branch.

2021-01-06 19:05 UTC, jfernancordova commented on src/InArray.php
>              }
Oh I see, I'm sorry for not realizing about this, I just trusted in the tests, thank you for the details, very appreciate @weierophinney

2021-01-06 19:32 UTC, merged

2021-01-06 19:36 UTC, jfernancordova commented
It was an amazing experience! Thanks for everything @boesing @glensc @weierophinney @Ocramius

2021-01-06 20:41 UTC, lahivee commented
thank you for your work on PHP8 support! when do you plan to release this?

2021-01-06 21:02 UTC, weierophinney commented
There's a few other PRs marked for the 2.14.0 release that I'm reviewing and helping complete now; hopefully later today, but it may be tomorrow.