PHP 8.0 support
laminas/laminas-validator pull request #79
Opened 2020-12-31 22:52 UTC by danmichaelo

Extending #75 to see if we can get tests to pass.

2021-01-01 14:54 UTC, Ocramius requested changes

2021-01-01 14:54 UTC, Ocramius commented on src/InArray.php
> +                if (! $this->isMultidimensionalArray($haystack) && array_key_exists($value, array_flip($haystack))) {
Discussed in the other patch: if `$haystack` contains `object` instances, this will break  due to `array_flip()`

2021-01-01 14:54 UTC, Ocramius commented on test/Db/NoRecordExistsTest.php
> +     * @requires PHP < 8.0
`@requires` to be removed

2021-01-01 14:54 UTC, Ocramius commented on test/Db/NoRecordExistsTest.php
> +     * @requires PHP < 8.0
`@requires` to be removed

2021-01-01 14:54 UTC, Ocramius commented on test/Db/RecordExistsTest.php
> +     * @requires PHP < 8.0
`@requires` to be removed

2021-01-01 14:54 UTC, Ocramius commented on test/Db/RecordExistsTest.php
> +     * @requires PHP < 8.0
`@requires` to be removed

2021-01-01 15:13 UTC, boesing requested changes

2021-01-01 15:13 UTC, boesing commented on .travis.yml
> +    - php: 8.0
Please add PHP 8.0 with `latest` and `lowest` dependency just like all the other stable PHP versions.

2021-01-01 15:13 UTC, boesing commented on composer.json
> +        "laminas/laminas-cache": "^2.6.1 || ^3.0",
Please do not add unreleased versions to `composer.json`. The BC breaks are not yet merged and thus there is absolutely no way we could assume if this package is compatible with it or not.

I am not sure why `laminas-cache` is even a dependency in here as even if I remove it from the `composer.json`, every test passes.

So you might consider just remove that package from here as it is not being used at all.

2021-01-01 15:13 UTC, boesing commented on .travis.yml
> +    - php: 8.0
Its okay to extend the `COMPOSER_ARGUMENTS` with `--ignore-platform-req=php` in case of PHP >= 8.0.

This package is not blocked by PHP 8.0, just some dependencies are not yet stating they're compatible but that has nothing to do with this package.

2021-01-01 15:13 UTC, boesing commented on test/Db/NoRecordExistsTest.php
> +     * @requires PHP < 8.0
We have to remove this as stated in in #75 
This test has to pass or we are not compatible with PHP 8 as of now.

If you want to speed things up, please consider creating a PR in `laminas/laminas-stdlib`

2021-01-01 15:13 UTC, boesing commented on test/Db/NoRecordExistsTest.php
> +     * @requires PHP < 8.0
We have to remove this as stated in in #75 
This test has to pass or we are not compatible with PHP 8 as of now.

If you want to speed things up, please consider creating a PR in `laminas/laminas-stdlib`

2021-01-01 15:13 UTC, boesing commented on test/Db/RecordExistsTest.php
> +     * For PHP 8.0 Library laminas/laminas-stdlib/src/ArrayUtils.php needs to be upgraded
We have to remove this as stated in in #75 
This test has to pass or we are not compatible with PHP 8 as of now.

If you want to speed things up, please consider creating a PR in `laminas/laminas-stdlib`

2021-01-01 15:13 UTC, boesing commented on test/Db/RecordExistsTest.php
> +     * @requires PHP < 8.0
We have to remove this as stated in in #75 
This test has to pass or we are not compatible with PHP 8 as of now.

If you want to speed things up, please consider creating a PR in `laminas/laminas-stdlib`

2021-01-01 15:13 UTC, boesing commented on test/Db/RecordExistsTest.php
> +     * @requires PHP < 8.0
We have to remove this as stated in in #75 
This test has to pass or we are not compatible with PHP 8 as of now.

If you want to speed things up, please consider creating a PR in `laminas/laminas-stdlib`

2021-01-01 15:13 UTC, boesing commented on test/Db/RecordExistsTest.php
> +     * @requires PHP < 8.0
We have to remove this as stated in in #75 
This test has to pass or we are not compatible with PHP 8 as of now.

If you want to speed things up, please consider creating a PR in `laminas/laminas-stdlib`

2021-01-01 15:13 UTC, boesing commented on test/Db/RecordExistsTest.php
> +     * @requires PHP < 8.0
We have to remove this as stated in in #75 
This test has to pass or we are not compatible with PHP 8 as of now.

If you want to speed things up, please consider creating a PR in `laminas/laminas-stdlib`

2021-01-01 18:06 UTC, jfernancordova commented on src/InArray.php
> +                if (! $this->isMultidimensionalArray($haystack) && array_key_exists($value, array_flip($haystack))) {
I'm working on it.

2021-01-01 18:07 UTC, jfernancordova commented on test/Db/NoRecordExistsTest.php
> +     * @requires PHP < 8.0
Fixed in #75.

2021-01-01 18:08 UTC, jfernancordova commented on test/Db/NoRecordExistsTest.php
> +     * @requires PHP < 8.0
Fixed in #75.

2021-01-01 18:08 UTC, jfernancordova commented on test/Db/RecordExistsTest.php
> +     * @requires PHP < 8.0
Fixed in #75.

2021-01-01 18:08 UTC, jfernancordova commented on test/Db/RecordExistsTest.php
> +     * @requires PHP < 8.0
Fixed in #75.

2021-01-01 18:08 UTC, jfernancordova commented on .travis.yml
> +    - php: 8.0
Fixed in #75.

2021-01-01 18:09 UTC, jfernancordova commented on test/Db/NoRecordExistsTest.php
> +     * @requires PHP < 8.0
Fixed in #75.

2021-01-01 18:09 UTC, jfernancordova commented on test/Db/RecordExistsTest.php
> +     * For PHP 8.0 Library laminas/laminas-stdlib/src/ArrayUtils.php needs to be upgraded
Fixed in #75.

2021-01-01 18:09 UTC, jfernancordova commented on test/Db/RecordExistsTest.php
> +     * @requires PHP < 8.0
Fixed in #75.

2021-01-01 18:09 UTC, jfernancordova commented on test/Db/RecordExistsTest.php
> +     * @requires PHP < 8.0
Fixed in #75.

2021-01-01 18:09 UTC, jfernancordova commented on test/Db/RecordExistsTest.php
> +     * @requires PHP < 8.0
Fixed in #75.

2021-01-01 18:35 UTC, jfernancordova commented on src/InArray.php
> +                if (! $this->isMultidimensionalArray($haystack) && array_key_exists($value, array_flip($haystack))) {
@Ocramius what do you think about this?

`                $haystack = is_object($haystack) ? get_object_vars($haystack) : $haystack;
                if (! $this->isMultidimensionalArray($haystack) && array_key_exists($value, array_flip($haystack))) {
                    return true;
                }`

2021-01-01 18:37 UTC, Ocramius commented on src/InArray.php
> +                if (! $this->isMultidimensionalArray($haystack) && array_key_exists($value, array_flip($haystack))) {
Nono, the problem is when `$haystack` **contains** objects

https://3v4l.org/uEHq1

2021-01-02 16:21 UTC, jfernancordova commented on test/Db/NoRecordExistsTest.php
> +     * @requires PHP < 8.0
Fixed in #75.

2021-01-02 16:21 UTC, jfernancordova commented on test/Db/RecordExistsTest.php
> +     * @requires PHP < 8.0
ixed in #75.

2021-01-05 08:13 UTC, danmichaelo commented
Thanks for the review, @boesing ! And to @ jfernancordova for updating #75 ! I'm closing this PR in favour of #75, which seems to be making good progress!

2021-01-05 08:13 UTC, closed without merging