Fix regression regarding InArray validator with boolean strict options
laminas/laminas-validator pull request #83
Opened 2021-01-12 19:03 UTC by boesing

|    Q          |   A
|-------------- | ------
| Bugfix        | yes

### Description

Fixing regression boolean `strict` option in `InArray` validator.

Closes #81

2021-01-12 19:05 UTC, Ocramius requested changes

2021-01-12 19:05 UTC, Ocramius commented on phpunit.xml.dist
> +        <ini name="error_reporting" value="16383"/>
IMO disable it selectively for the few tests where this is expected

2021-01-12 19:11 UTC, boesing commented on phpunit.xml.dist
> +        <ini name="error_reporting" value="16383"/>
Do you have a recommended way? I always struggle regarding this as there is not simply `self::ignoreErrorLevel` and invoking `error_reporting` in the test itself does not work...

2021-01-12 19:13 UTC, Ocramius commented on phpunit.xml.dist
> +        <ini name="error_reporting" value="16383"/>
Perhaps setting an error handler? I don't have a standard approach myself, as I avoid adding runtime deprecations as much as possible, so IMO here I would not have raised one at all.

There's an `expectDeprecation` or such in phpunit BTW.

2021-01-12 19:15 UTC, froschdesign commented on phpunit.xml.dist
> +        <ini name="error_reporting" value="16383"/>
> There's an expectDeprecation or such in phpunit BTW.

https://phpunit.readthedocs.io/en/stable/writing-tests-for-phpunit.html#testing-php-errors-warnings-and-notices

2021-01-13 17:18 UTC, weierophinney approved these changes

2021-01-13 17:20 UTC, merged

2021-01-22 11:32 UTC, shandyDev commented
@weierophinney 
Guys, please push release v1.14.1 to packagist, it is missed: https://packagist.org/packages/laminas/laminas-validator

2021-01-22 11:39 UTC, Ocramius commented
I forced an update on https://packagist.org/packages/laminas/laminas-validator, and it states:

 > Last update: 2021-01-22 11:38:59 UTC 

Probably something stuck over there?